-- generated by KeySteam
-- update time: 2025-10-29
-- app_name: 迷失混沌王国：永恒之骰

addappid(2564520,0,"554829d24add8723f4f110fb7b971df70776161336ac9e6ad9f74cbfa1500a20")

addappid(2564521,0,"4b679f8c7ffc59c1398369a7bb72987e78717c22d81ec186eb11bb0cc0e5f6e8")
addappid(3478380,0,"08b4f767f1591c4c96ec034dd7c78d0d442ac1d6c39586fff1ece5f94a7e4e6c")

-- DLC: 4/4

addappid(3478380)
addappid(3573930)
addappid(3857960)
addappid(4040310)