-- generated by KeySteam
-- update time: 2026-02-10
-- app_name: 姊妹的侍奉

addappid(2564050,0,"8934e55ef030d66acc21788bcd15f1e51c00a4e800d33b79fad563e814cb1651")

addappid(2564051,0,"5274d5fea88266fb46b3c26b8977b20b92bed30795363a49b3493081a3c571dc")
