-- generated by KeySteam
-- update time: 2023-09-22
-- app_name: 怪物2

addappid(2575840,0,"db785a6caadc032377f13b35a4de85f515e9da4c4404c4775b971859021f4d26")

addappid(2575841,0,"b49c98caed7a7e6815c73079bcc30320118e8c097a28d07b4b316422abad247a")
