-- generated by KeySteam
-- update time: 2025-11-29
-- app_name: Sweet Life ~~幸福的每一天，直到被寝取染上为止~~

addappid(3883830,0,"02f238ff85e849ae664dc3f16e6144d8178eb7119bd501b412761ec958e1dc58")

addappid(3883831,0,"7b7d2e9f27a07eb5ac666b9c45827beb9dd92579c6a2d2856eb47141177a155b")
