-- generated by KeySteam
-- update time: 2026-05-04
-- app_name: Gamble With Your Friends

addappid(3892270,0,"792fb0e3dedf02f8756774da38656b5b7212250cf8e33822e6b27199b2530385")

addappid(3892271,0,"90695be6010d5ec2e8890f1d742357316f4d5f74a8a9d22b2ae076b184797167")
