-- generated by KeySteam
-- update time: 2025-08-26
-- app_name: 魔物联盟自走棋

addappid(2906030,0,"4238c67209e9a9fb984ee503a7b22fea914c23615ef9c74644057fca937c0c7f")

addappid(2906031,0,"7c7c8fe085d6c210bb417a7e159fbc49394934cf71b81eebb727933d83c79924")
