-- generated by KeySteam
-- update time: 2024-07-01
-- app_name: 魔王的地牢

addappid(2911130,0,"53e77ece56da75450310c6309ca07490b24ee4cd66159590465c892a199bac70")

addappid(2911131,0,"37656022a680305f5ebb0212d9c5bdc7afd641bb957c8fa92da69b7634074b9b")
