-- generated by KeySteam
-- update time: 2024-05-23
-- app_name: 恐怖之眼

addappid(2633640,0,"5e6598152f55ffe7118d037ca36135f336479352dbdef133726a59b7bde62cbc")

addappid(2633641,0,"354896175274e7b6283e32965671d842b6ebd9fa2e8fb78d15c7b833e7d21ebc")
