-- generated by KeySteam
-- update time: 2025-04-10
-- app_name: Inari

addappid(2639100,0,"3501fe45b06f7c3a2f81a9c1f9eeb56c57096aded6a9a9d2c54a52e10ee761ff")

addappid(2639101,0,"21f31c8adf14db935b09d4d1a9ea8e781df503db08605f5daa84515f3dd6f10c")
