-- generated by KeySteam
-- update time: 2023-08-30
-- app_name: Perfect

addappid(540740,0,"3b1a7ca1b5f81f86d26395216930c0e23d640f490be62731854673d8c9360123")

addappid(540741,0,"4afafeb8d471530f7df742747424f000503228009b6e7b30bf4c510f2feca3ab")
