-- generated by KeySteam
-- update time: 2021-02-09
-- app_name: METAL GEAR SURVIVE

addappid(543900)

addappid(543901,0,"6660062fa5608dd613cb712c1e4f4d930be90938794ff33a3963dab922c843bf")

-- DLC: 5/5

addappid(631800)
addappid(631801)
addappid(631802)
addappid(631803)
addappid(802030)

addtoken(631800,"13954688594577025696")
addtoken(631801,"3048252096991024816")
addtoken(631802,"16416525363964487207")
addtoken(631803,"12865724625726360833")
