-- generated by KeySteam
-- update time: 2024-05-21
-- app_name: 闪客快打单机版合集2021

addappid(1540150,0,"1483a9383ba8caad228d5de2206b333d696a49718aadbedc45dbdde35fff2a9a")

addappid(1540151,0,"6883b38af8d6b809129f30eb503a8f7e58d51698dbd30eb035837e20b7d95add")

-- DLC: 1/1

addappid(2917650)