-- generated by KeySteam
-- update time: 2021-03-19
-- app_name: 扫雷冒险谭2 ~露露姆的冒险~

addappid(1549240,0,"b48e216203ca01075331a400e94541d30b64534fc486d7fe12363f52c4932bdc")

addappid(1549241,0,"2505f738277d071db4929d2714d4d47daeec65d6232a1a8937955351aebd3393")
