-- generated by KeySteam
-- update time: 2021-04-13
-- app_name: Childhood Friends

addappid(1549160,0,"7b91fe95f052569b42d2e81dcb2e2f263b417c150d1b4c3035ad2f52c5b672b5")

addappid(1549161,0,"b87cc909d1500753822fb83969e3304b2e66e07a6296037d6d59834621480bf9")
