-- generated by KeySteam
-- update time: 2023-01-09
-- app_name: Little Orpheus

addappid(1558930,0,"a9b8fff12adad28f29fd6b72db656d37a35cc10473f75345438d9d998fdef269")

addappid(1558931,0,"6333d7f5a890e5fb114c2230c12d271b82d68462f3ec693be710765ffaf34972")
addappid(1903260,0,"920e53ffbbd0e2e20c460fc9313a0ba0b26f7974a309fd7db2d10640d044bcc9")

-- DLC: 1/1

addappid(1903260)