-- generated by KeySteam
-- update time: 2020-03-30
-- app_name: H-Rescue

addappid(1058530,0,"9c888e78a4ede872a5df812113d865aede9d42fd17234aa3504bcae1b3ad6d0c")

addappid(1058531,0,"e1242c838d1436b5f4d5d6f154642821469a0742e696c5dc0ae6df058050813a")
addappid(1221340,0,"9cdda93c1089dc5475ec0923d740cc0c95cd589dce1967fb4f124c3c4993b023")

-- DLC: 1/1

addappid(1221340)