-- generated by KeySteam
-- update time: 2025-06-16
-- app_name: Hard West 2

addappid(1282410,0,"c023b6d970615ef2cc6094d98f889221a7121804782a72038265ad9ca9155be4")

addappid(1282411,0,"ed806de682e2ef949547012e45206c1f39611d45a31c4559c43e2145b9a49283")

-- DLC: 2/2

addappid(1953460)
addappid(1991380)