-- generated by KeySteam
-- update time: 2021-05-28
-- app_name: 勇者斗恶龙XI S 寻觅逝去的时光 - Definitive Edition

addappid(1295510)

addappid(1295512,0,"c4f1eb51eed857dfea8f5d5cfdd2ebcc210d2497176457360b5c6a61e312d6b6")
addappid(1295513,0,"940f6f87ded1c6f17229cc6e898c946f8ae111e0f74214543e0d73384711c0f2")
