-- generated by KeySteam
-- update time: 2025-10-06
-- app_name: Mystwood Manor

addappid(1863670,0,"d625ee13e5ffd5a72f37a7d4edbf6cb8170d2e2123711fd14d8d68bbb2a43e15")

addappid(1863671,0,"48f0861f50d491d54e04a73a1c18681e5ac8ab1f8d2f7e5ee3e8be1e3d6de26d")
addappid(2170070,0,"074c968debe442b6e36b663082160a3a772eac1dbb79a66dab92fce4fd916533")

-- DLC: 1/1

addappid(2170070)