-- generated by KeySteam
-- update time: 2023-07-17
-- app_name: 末日机娘

addappid(1870310,0,"363ac6ef82840ffe0ab6c941f37f68e909f4a8005d368701c358743f33712fb6")

addappid(1870311,0,"a3d341658a9283c196433c193eaf54cb9f02505dd8c33bd4f6a966ae86d34cd2")
