-- generated by KeySteam
-- update time: 2026-01-03
-- app_name: 工作日常

addappid(1872510)

addappid(1872511,0,"02d88f300eb36e0c4c6f0d680738370f3b278de3bce831fa48c99adf5190d511")
addappid(1880270,0,"63457f91cfe619747737820be6b989031c5913d816621d03d2f275b566713602")

-- DLC: 1/1

addappid(1880270)