-- generated by KeySteam
-- update time: 2026-01-29
-- app_name: 有这么一个家伙

addappid(3687630)

addappid(3687631,0,"88979c4713587c583a1aa6d1bdf89441bde7e6aa52ca42beec77f6c276fccc3f")
addappid(3868111,0,"1d707ca8e513b9e6d8b78399b82b3d83a068120581e699dd8d585debf122775d")

-- DLC: 1/1

addappid(3868110)