-- generated by KeySteam
-- update time: 2026-01-31
-- app_name: Sakura Succubus 10

addappid(3699940,0,"d514e41ac6c810143a2a5c616428e9c9f2ec454a71ff3c8542b8dad8bfe3ba83")

addappid(3699941,0,"686f0b866fc918f97a5b9b5c71d0e15f891d712ccc88507207e201e04d94e6cf")
