-- generated by KeySteam
-- update time: 2025-12-18
-- app_name: BROK Natal Tail 鳄鱼侦探布罗格 – 尾诞节，新的圣诞

addappid(3361210)

addappid(3361211,0,"046f7c835962865b40422da38a9ea34250e3f6c00745b9b6b27c014c07d01c42")
addappid(3365410,0,"081e3d9796f7572ebb75dc1a1ef8048885137d6b8738634a3ce27299947968ca")

-- DLC: 1/1

addappid(3365410)