-- generated by KeySteam
-- update time: 2025-09-06
-- app_name: 巴夫罗与色情陷阱迷宫

addappid(3367320)

addappid(3367321,0,"bfc8979e5fe4563fb669cb611daa9a7a0119b144c1cf4cb940c741b84fcbdc21")
addappid(3367322,0,"bebd983adfdfb79f1e0ede40f0b90fe19d5b8442b02e443a668439c342bd0502")
addappid(3367323,0,"2c89d48219d9baaea0602001a2da3dfe845c5ce6880c2ae221b8812827dc6bec")
