-- generated by KeySteam
-- update time: 2026-04-01
-- app_name: 颈椎病

addappid(4000090,0,"11285b2b7435f9604876dd69afd5d9d23c5667ac729f42f84a6cb816aec88ce7")

addappid(4000091,0,"51546e23e8568339c45f4408bb1ac7582952d4a77a4e84e3b3cfa2b57b9ab51d")
