-- generated by KeySteam
-- update time: 2025-10-31
-- app_name: 蘑菇岛打工日记

addappid(4013460,0,"947f6f9a96dab7797c1b93c905f4b5cd7c9d2e51820d2b6116bcfce9e717811e")

addappid(4013461,0,"b6d2cd121138a1064eac0083dca2a08a0e015e5a01d000a1e88f864880771054")
