-- generated by KeySteam
-- update time: 2025-12-18
-- app_name: 天使台球吧

addappid(4013440,0,"22b0cb53f3d41199be41986437d26fc26fd3dffa76175895ed130ccd5dde4ea8")

addappid(4013441,0,"54100fe5e6ceabda3c3e991c60fd60195be802820efbcd437fb0c3660b7756d2")
