-- generated by KeySteam
-- update time: 2026-03-22
-- app_name: 那个夏天 - 小涵的暑假

addappid(4016670,0,"2ff4a57be14c1aeaef95c1473e2b6119fda3c5121ef2582bfe88155a09fcfcca")

addappid(4016671,0,"0525a1b7a998434da92794325faab1ad78ab122881c6cffa4cb68bb9534b51c3")
