-- generated by KeySteam
-- update time: 2026-04-16
-- app_name: 神明也没猜到结局

addappid(4017820,0,"1c1369fc6b3edd5dd59873a01cd73cb0114d08f5e3032adad9f55ac5391a66d5")

addappid(4017821,0,"057ead8152b6fce442476d745d3d48e420d97971680196258a3369fa4951cafe")

-- DLC: 0/1
-- missing DLC: 4192610
