-- generated by KeySteam
-- update time: 2026-05-08
-- app_name: 色系战记

addappid(3470370,0,"9f9da5bf89d4cd8ab4c29d729ce572fe3dea467c4a9261534cf3f932e2b623fa")

addappid(3470371,0,"301b398234f4ddd86faab7fdc4438fd6518449d2f988847d96bb0aa26a18d98a")
addappid(4660521,0,"c53a1d62371bd4ab4ec4a157f993f0cad256e412a6841efba3ac6124f92604e3")

-- DLC: 1/1

addappid(4660520)