-- generated by KeySteam
-- update time: 2026-04-14
-- app_name: Slaves of Rome

addappid(1380070,0,"dc44dcfce7358c32686a81984c7badb2b91b0c41833c620cd10d2c0ed9509b32")

addappid(1380071,0,"35bbeb039ac8fcae5ecedb7bf9592c5fbead89187c78e7fca100ccc0b85d39a9")
