-- generated by KeySteam
-- update time: 2023-05-18
-- app_name: Arcade Paradise

addappid(1388870,0,"f266c7484df7898cf55ee71d7e957f8ab64c6d405c0440144edf36300e88aa8d")

addappid(1388871,0,"83cd56b908dfe50adfc7684d1f0dff29d2c72f42f43728b7bc96acb1fb042bed")

-- DLC: 8/8

addappid(1986510)
addappid(1986511)
addappid(1986512)
addappid(2217400)
addappid(2217401)
addappid(2217402)
addappid(2217403)
addappid(2217404)