-- generated by KeySteam
-- update time: 2024-04-08
-- app_name: S.H.E.L.T.E.R. - An Apocalyptic Tale

addappid(1394100,0,"cc45f50597da197326d9e89f334d1af2396a6e802678adca8a7bf5ddd5ee2e44")

addappid(1394101,0,"03658f06687f568913af13ba249bf7b56f1a93a54c5294e516fb9adf0bb14fb9")
