-- generated by KeySteam
-- update time: 2024-12-07
-- app_name: I MAED A GAM3 W1TH Z0MB1ES 1NIT!!!1

addappid(1800730)

addappid(1800731,0,"3ff94f6cf172807ac3f14b901918c27a80dc94ae1cbd8ae557be98c51a9c9349")
addappid(1800733,0,"1fe3b593be6effa72bbfadc2fa7bea400ce34606a07131a31063d9a9e45c32e9")
