-- generated by KeySteam
-- update time: 2022-09-24
-- app_name: cursor0x0

addappid(1800340)

addappid(1800341,0,"30c71a6051cc73b2fbe6ef5ebec2292fca1a1ceae0b56dfc016d0fb4a1c1b8f8")
addappid(1800342,0,"c48eb2fce23ae8899a527e649e240597bac6376593a286bef60417024414674d")
