-- generated by KeySteam
-- update time: 2022-04-25
-- app_name:   Devil's Dungeon

addappid(1801470,0,"4db57784b0e28fe01ad8e7839b74359d27c57a096d3a6206524411831640dc6a")

addappid(1801471,0,"3d5ddcf9c2eba14b1f1c890cd1c4a5c445d35e6b6eda74c7eb7f67140e880c1b")
addappid(1813510,0,"a08368b568b4d67abb143610c8611ffc242610c90a91cc055639ec8b76c4ee6d")

-- DLC: 1/1

addappid(1813510)