-- generated by KeySteam
-- update time: 2022-10-28
-- app_name: Usagi Health Club

addappid(1806630,0,"698f2c0587f6d1a0136f3d6388db61d38d36c8062e1cef0106f14433f6895622")

addappid(1806635,0,"b4c369abb064394848b8185624bd3978e54256d13c0a0bbf296e128a291e9f67")
