-- generated by KeySteam
-- update time: 2022-06-27
-- app_name: Scratch Girl

addappid(1814490,0,"266f5447b0761726153bee67fd4a09344eb53bd735d666fc2eb4e22f8d6fd692")

addappid(1814491,0,"090f02da0d97a277694eb66782074a24bbc7cc43da8c189397aa00d77c8957e4")
addappid(1830550,0,"c644973d058360276bcbbb1ec6c97f8b05f447dec6ba08ab275f2444b0693f97")

-- DLC: 1/1

addappid(1830550)