-- generated by KeySteam
-- update time: 2026-05-02
-- app_name: 息风谷战略

addappid(2646320,0,"72c776dde4e41be4d4d4d23e9bc5e73bdea9fb7386ed44772eaeda0825803aa5")

addappid(2646321,0,"788707cb8c67eb748233059f2da076e2b585eb95d64774c323e01295bcc8d968")
addappid(4659121,0,"72163cac8fdb67346b16fdcf7a7771aa07ade887d8547db59c7d4b9ff3103abc")

-- DLC: 1/1

addappid(4659120)