-- generated by KeySteam
-- update time: 2024-09-18
-- app_name: Agent Mirai and the Submission Machines

addappid(2652490,0,"8f3850d45f52bfc1967361c180ad00ab88f694a33bf42a9fd0bc9d6c44064fd7")

addappid(2652491,0,"6e24f3764bd3075c81f7d16c37a20481526acc72c2c6765bf80ce05e179b0d50")
addappid(2652492,0,"0f8ef832f5c52747644804bd29339c52e49a4da970f673fa3eab27bd0a573e46")
