-- generated by KeySteam
-- update time: 2026-02-13
-- app_name: The Witch's Warehouse Management

addappid(3981660,0,"4879a9d6afab35ebf0938037c1ba6e0c0b3961a268811931a7c2074ab25e1915")

addappid(3981661,0,"a1e5d90dc0b15d60964cafc83825f75c631227067ea35555226718fd61000a36")
