-- generated by KeySteam
-- update time: 2026-02-16
-- app_name: The Demon King's Daughters

addappid(3981670,0,"091d8775f957d416e3098669b7870a6608488af3f55eef3699d662a04ac145e5")

addappid(3981671,0,"7850d42699135ee28c810ee6bb0506ae27f20daa79de9362bc12234b3a4b8093")
