-- generated by KeySteam
-- update time: 2026-04-04
-- app_name: AI Script: Infinite Text Adventures

addappid(3991060)

addappid(3991061,0,"a63156f5b46905c7a08d363da3afe8b308d01794d84984da21e04f4a4558e8f9")
