-- generated by KeySteam
-- update time: 2026-05-15
-- app_name: 女儿国的诅咒 The Curse of Womanland

addappid(3995110)

addappid(3995111,0,"622021b638c5b6f45c5e7d5cbaa8ab9ff928204817b8424f09012d79167da386")
