-- generated by KeySteam
-- update time: 2026-03-19
-- app_name: 恋爱吗？我家猫会后空翻

addappid(3998800)

addappid(3998801,0,"f338475c0e275d289d04ec416d7ab6b6c5127619d5ceae3022bdeef6eef2a2bb")
addappid(4223320,0,"ce4ec9d433975e3b8557f8a016315342c36def7d126ed860c41c3ac280de06d3")

-- DLC: 1/1

addappid(4223320)