-- generated by KeySteam
-- update time: 2026-04-15
-- app_name: 三国朋克 - 爱与破坏之神

addappid(2505590)

addtoken(2505590,"16906287408241698490")

addappid(2505591,0,"fb14f1b6d07a571471a6f3b3f4f60bb69aa96ed93b6aca3b1c79640bcf3b405b")
