-- generated by KeySteam
-- update time: 2026-05-20
-- app_name: 归零巡礼：亡谍镇魂曲

addappid(2863680,0,"b0deaab3529583327b89558f4eefca8cdaa31f2e94d8148eb1a7e4803b3af539")

addappid(2863681,0,"6f8570b7626034b90d4244ec942a2e30b85f4a6c139c76622a364117e5e49be4")
addappid(4719150,0,"9ede90e3a696df35e824df54f8a882256941165d2b283859e3a422c7dccf75bb")

-- DLC: 1/1

addappid(4719150)