-- generated by KeySteam
-- update time: 2026-03-25
-- app_name: 寻宝湾

addappid(2867470)

addappid(2867471,0,"06a5aa47c3631271b8ca5d7ac9607a1c71e02e2a962eace8401a14d7957477cc")

-- DLC: 1/1

addappid(4110980)