-- generated by KeySteam
-- update time: 2021-12-08
-- app_name: Maneater

addappid(629820,0,"e67d50c085c3a392b182a87c69e936f89f0f6982e146bc3561e356644fa2c47c")

addappid(629821,0,"177cc05630810840243d069011bd1956c1e0180b4d4d9eeb1c3be213e95dd167")

-- DLC: 1/1

addappid(1611940)