-- generated by KeySteam
-- update time: 2018-09-29
-- app_name: Bionic Attack

addappid(632380)

addappid(632381,0,"819752bd9855fb591885f29dd00373fb355fa4de49357127e0445278c7fa313f")
addappid(632384,0,"45e4f29e3f09c0359392f1528a22bae7ae2e7c3a70c50dab82f1d8403d2cdda6")
