-- generated by KeySteam
-- update time: 2022-12-23
-- app_name: Majestic Trials

addappid(638060)

addappid(638061,0,"2c6a62a0954ee67d3692b48ff58249382b58a00014a6421305ecf9e58ab1dad7")
addappid(638062,0,"684358856601e15f2ecad2b2975a14a792615ebb6e7d367c655c0a52e84d9bcd")
