-- generated by KeySteam
-- update time: 2019-11-01
-- app_name: DEEP SPACE WAIFU

addappid(639790,0,"99554963fe6604dc7e1f15638535b96a8b31fbf129960c10e45f3773cda15f62")

addappid(639791,0,"f21b6b8d1f9faf07662ccc922077de3e63ad35ee2067435f3b2cb94bc31c6207")

-- DLC: 2/2

addappid(648930)
addappid(701531)