-- generated by KeySteam
-- update time: 2024-05-29
-- app_name: 边境

addappid(1364020)

addappid(1364023,0,"d11348db49f59c7fd026463c0c69ddd3e9071abb22b624a9441b8ddb75e53656")

-- DLC: 4/4

addappid(2374920)
addappid(2374930)
addappid(2374980)
addappid(2386820)