-- generated by KeySteam
-- update time: 2020-12-20
-- app_name: Cyber Crush 2069

addappid(1379830,0,"1c28a6cdb64be9a235cf2ec7efc4234f8bf8008505fa6c5e03f482ee70a16573")

addappid(1379831,0,"afe1d64057d4621d6a1facca5f9945f522cee0ad51ccaa20db93a80615ff1239")
addappid(1442210,0,"a3e0c948e7594d9b6360631d2dec9265b6304d9174442482e929e18a9c513234")

-- DLC: 1/1

addappid(1442210)