-- generated by KeySteam
-- update time: 2019-04-03
-- app_name: NEVERMORE

addappid(924540)

addtoken(924540,"17494878085266722090")

addappid(924541,0,"6f5207aae9cc7eb9aaaa7da51d8ae1b4201333d2c3fde582b74ed3df1b453061")
