-- generated by KeySteam
-- update time: 2019-03-14
-- app_name: Count Logica

addappid(928660)

addappid(928661,0,"3a65358390800bb1b033459d0212b2dd60657f339f6f7f6fa941b253f4c1b27f")
addappid(928662,0,"61a07cf8b4fa2ff0bbfca1762a91199722951b88738a10844ffde2ed5bf9453d")
