-- generated by KeySteam
-- update time: 2026-05-23
-- app_name: Hillshade Farm: First Harvest

addappid(4026790)

addappid(4026791,0,"aeb90b0eecee2621fd8ff40a04018cf00db4166b9127f86e3968bd1066a28f42")
