-- generated by KeySteam
-- update time: 2025-02-28
-- app_name: 王国英雄

addappid(259550)

addappid(259551,0,"31110b860af7cc31944bf178cc08270666a0bf070919feb247094ebe94b2b81b")
addappid(259552,0,"409e698813c8381e0faf7875df9f451694307b0a2e99e341aaee89a4a89bc035")
