-- generated by KeySteam
-- update time: 2020-01-31
-- app_name: 港诡实录

addappid(1178490,0,"ea57da631125d93336e873e1152ea4f9c07ffc328b37558414253cb7e7ab39a5")

addappid(1178491,0,"05de198526b71687f617c6a476b9829f9deaff99b590c33599e4cc1ba63ef987")
