-- generated by KeySteam
-- update time: 2025-09-17
-- app_name: 妖狐的深夜直播

addappid(3241760,0,"98e6d74e0ff089a782df744e3bafc4974acc35f0c65e25ca43beb2b8cbb08e84")

addappid(3241761,0,"877ea4fd65b7150aa3944c78c3840696cec669b06fee87e9965fa6665daaff1a")
addappid(3745131,0,"7ef6759f6a487c1f1e91ce704482274f14d1b359c43c78c915a233572a8ed01f")

-- DLC: 1/1

addappid(3745130)