-- generated by KeySteam
-- update time: 2025-11-27
-- app_name: R.E.P.O.

addappid(3241660,0,"f647b73aa575d1ab056b68c1922a108a7bdeb79f6d472db883bde0a2ff307f48")

addappid(3241661,0,"0a0fcffb2de6fb0fa6caff076a5a8cb960903d17320968d5c042fd5a4f9ad2ad")
