-- generated by KeySteam
-- update time: 2026-05-07
-- app_name: 历史模拟器：崇祯

addappid(4304230)

addtoken(4304230,"6733678450081382879")

addappid(4304232,0,"275edfe8e4a0741473d54bc820774a03cae9efc2b8effae79d5fc8495af89330")
