-- generated by KeySteam
-- update time: 2026-03-05
-- app_name: 我在異想世界转生，鸡巴长到跟这游戏名字一样长

addappid(4233640,0,"3994261a6741180fb733f505d119d2f01dc631d2614192fba38b710097f9ad33")

addappid(4233641,0,"5ef5c0e92fe503617db7239fee34b45e37c3364d49dd2998c09122dee4672d50")
