-- generated by KeySteam
-- update time: 2026-04-21
-- app_name: 艾莉泽与迷离的木偶

addappid(4237200,0,"583a2cbccb9119f5077cabc90a8e66253e0cff7cde5f90a126379ed01a5ac73f")

addappid(4237201,0,"a534c27216c4168f4ead2a025d16e835733e9dcb1695b9a5cc31c93898bfe5af")
addappid(4237202,0,"7aac0b8d2bac38eecb526cdf3a1c94e3f48150a4f7f5c6a8051fa3a31ed0c302")
addappid(4237203,0,"b8cc28ccaa097e0c117ce78c3d2efa2eeb2711af70993eadfcbc8d43e69304c5")
