-- generated by KeySteam
-- update time: 2025-10-16
-- app_name: Sir Whoopass™: Immortal Death

addappid(1240590,0,"fa2c1267504f8c89b546f9c67c96dbece61a6cef996b71bc36203823c2deea02")

addappid(1240591,0,"81a27b9cc381a91b16ba3419786c73517a68eafb06e1084a391d78b92f03f5c8")

-- DLC: 3/3

addappid(3181710)
addappid(3851940)
addappid(4035100)