-- generated by KeySteam
-- update time: 2026-02-03
-- app_name: 焕然异星 Terraformers

addappid(1244800,0,"a4970b70725989a82a391c80578ef2218763bda25ee5816a72ecb5f5ced0140d")

addappid(1244801,0,"8497f1f2c3d208f4150b210cfc9f1b5281d74a3b2e5e209a235baa4ad9553ad4")
addappid(1783650,0,"0474504e1c09e61912b386782d3e567401170d2a93feb96f49fadd18746ec18f")

-- DLC: 4/4

addappid(1783650)
addappid(2646850)
addappid(2779050)
addappid(2779060)