-- generated by KeySteam
-- update time: 2026-04-12
-- app_name: 银月堡

addappid(1246350)

addappid(1246351,0,"b1dc8416c711efe0c5da1a4b62b8800a926fe330ef67e2abb0edb042596d1383")
addappid(1246353,0,"d44fc5e04425f4ce0767f3290c99bb4a227f319df9564f71cf57ea4e26fa685c")
