-- generated by KeySteam
-- update time: 2025-01-25
-- app_name: 王国英雄：失落传说1

addappid(1249130)

addappid(1249131,0,"876a9d14cb19eda18399739f840c8c4043dbf5554c1cf5076b7fc9f8f52e382b")
addappid(1249132,0,"db077e1219abfa3723dd8bcd855a5b014a97c8f89124786f2aef2afc2c3f90d0")
