-- generated by KeySteam
-- update time: 2025-02-07
-- app_name: Rogue Legacy 2

addappid(1253920,0,"faf4473101b67723291273185bbac2ae3109f6cf5f0dd191c3872fc29c474652")

addappid(1253921,0,"8f8731b760af31be5b1c527004d297c3d91ea86806d6658624250393dcdfaa78")
