-- generated by KeySteam
-- update time: 2025-07-21
-- app_name: Days Gone

addappid(1259420,0,"a84c754cff9b4845e7575ad3155bd88d2cacd91bf1cad7137adc1b612b94df3b")

addappid(1259421,0,"3a92a76d80b16038abe5b2831f554a22120535ab039dbde663a70c8b52afe11b")

-- DLC: 1/1

addappid(3238470)