-- generated by KeySteam
-- update time: 2025-01-06
-- app_name: 3444360

addappid(3444360)

addtoken(3444360,"3683104460942029284")

addappid(3444361,0,"915a78274db2a3c8d34bb1661b7d3b648522a3d87c9de60c2d647cfb6869bf31")
