-- generated by KeySteam
-- update time: 2026-04-13
-- app_name: 信的折叠旅途

addappid(3448430,0,"210c680d8c73bfd5e4326161f52b5b9a10fb1cd078aabdb15d372577d9baf85b")

addappid(3448431,0,"7fde477b747ebc27b2c9369a19f170560850302c582181d77cbd7f3dfe35caf9")
