-- generated by KeySteam
-- update time: 2026-02-06
-- app_name: 张伟和他不太好说的二三事 2

addappid(3427110,0,"113cbe1898a690688563bf7f1ab50f89714dae506db8a2b2aaf1e2ee8baa4494")

addtoken(3427110,"16681032175418277999")

addappid(3427111,0,"ba6719cf9f39eddff2b55cc120441edf1003ff5bf1dcfda639d28696fda6cdc7")
