-- generated by KeySteam
-- update time: 2025-11-20
-- app_name: 消灭！马赛克！

addappid(3436370,0,"adacab0b8128160886dc16c7844c5be1d66bc6dd5cb9d0e44774fdd9961b5fd2")

addappid(3436371,0,"f0c39776c0758a187e9058195509b461459b71b32173a809999ae0974bc57c52")
