-- generated by KeySteam
-- update time: 2026-04-30
-- app_name: Sledding Game

addappid(3438850,0,"30e1f7e188e92cc3ddfe88f8da2ddd9201e70d77603ac4bc798e055b2fdb91f1")

addappid(3438851,0,"4f2a0854d927f1098bcc4ef65ce87280d5779230d0ce4a79549a990e7a04f2a7")

-- DLC: 1/1

addappid(4527730)