-- generated by KeySteam
-- update time: 2026-04-23
-- app_name: 权力的游戏 : 国王大道 Playtest

addappid(4514720)

addappid(4514721,0,"d9e2d31b0f9797245772e9d7b505705f7329e671bf8aeda3a98f34d6ae6cf31d")
addappid(4514722,0,"e38f3671a0da91b8b740174031a24c1cb01d60405cc33284a704d5fd0f7e1692")
