-- generated by KeySteam
-- update time: 2018-01-18
-- app_name: VA-11 Hall-A: Cyberpunk Bartender Action

addappid(447530,0,"3834301957782fcbc360ddce377a704347e5bd6245c3f611452aead68fc54367")

addappid(447531,0,"47fcb0672e67462091fdc31eae398a3710cdde69f7ead7e9addf905b627df0d7")
