-- generated by KeySteam
-- update time: 2022-06-17
-- app_name: 最后的仙门

addappid(1942440,0,"1231842ccdd4e29329db6321b0e1e5c78da6617073b2ae1b7dc312d0f6d4e8bb")

addappid(1942441,0,"8ddd156bd3bf1ab85224bdb5e8f57c9b9ecb0c0a86105b5bc61fcfaabbd7c5e3")
