-- generated by KeySteam
-- update time: 2024-01-29
-- app_name: 枪灵少女 2

addappid(1948700,0,"6a98c8651eb34d6cf2d10bac6cae565c533292c8b3e04be471210b47e073065f")

addappid(1948701,0,"431609d09f4d239805b1e8db7e06aaa8f50e084a9330b6eeec7c4b2346ce22c0")
addappid(2102830,0,"a2c34f5af81ee188d5f64097f561647b4ab8bd1145f4dbe5d001a508a40d25a6")

-- DLC: 1/1

addappid(2102830)