-- generated by KeySteam
-- update time: 2026-04-08
-- app_name: 鬼山魔音爆发 - Whisper Mountain Outbreak

addappid(1953230)

addappid(1953231,0,"c52dabd72185ea327cf8203293b4ea730984114a8b183f1535e9b5a83410a086")
