-- generated by KeySteam
-- update time: 2022-07-18
-- app_name: 真空战姬

addappid(1954640,0,"354519c8265f00ad440676b451a3b97a5758c433fb4eff0c8aab4305749c9e9c")

addappid(1954641,0,"e0c7ad606042904e2a9a195579febc7324888a14f18c2a608b33654fca29c63c")
