-- generated by KeySteam
-- update time: 2023-12-06
-- app_name: 雪色暗号

addappid(2307160,0,"4d467890313f7275672a41b7a2f2e51b1c057d915c114bed45baf12c4a6fbb57")

addappid(2307161,0,"8092221a74da7557f0f6af2f0190b9f9545a609ecd48d0e3fdc77c450b833b27")
