-- generated by KeySteam
-- update time: 2023-08-01
-- app_name: 花街万事屋

addappid(2308400,0,"3636c6f59c02cc3e5c772bda9d695e76e04782c6ce18b2bf982523ea706db032")

addappid(2308401,0,"b45ab06805b23ae57e7e83114f23901337e749c4bb8b3e568119d36585c45e35")
