-- generated by KeySteam
-- update time: 2019-03-08
-- app_name: Devotion

addappid(1006510,0,"bdb8e917cb6ebcdbb5ef5a98898977a000c89c6c1d3e89b5009126ca383bf7ce")

addappid(1006511,0,"b0515ee5a374e6f06d1e93799d0bbec8efef4f9a2d74b40ffe98a8a07d710489")
