-- generated by KeySteam
-- update time: 2024-06-27
-- app_name: 重生边缘 国服

addappid(1008080)

addappid(1008081,0,"d8e5fe395c03c0998ce33a882c7ee4cbece04a5c210a55ee1ab6e8b559ff5cae")
addappid(1008082,0,"bbf81f8e36b1f6b3cda09db636d09f5923d7ae15691daded895beb7f84003e68")

-- DLC: 3/3

addappid(2436610)
addappid(2490070)
addappid(2519330)