-- generated by KeySteam
-- update time: 2019-06-06
-- app_name: 亡国公主爱丽丝

addappid(1015800,0,"b82ecd628245f38b91af8e83569087583dad62eefaf2b6794607e91f361831f7")

addappid(1015801,0,"ffc94a35403d38734ad9270a96e1dcc4c9f3dfeabe67931e71949aefef4501d5")
addappid(1015802,0,"cb69ea9448f2d6937df817724b2c615c11f4ae242eaed150aead1511965c75fb")
