-- generated by KeySteam
-- update time: 2026-01-07
-- app_name: GNOG

addappid(290510,0,"55344894f31ba0eb845ffe0353e5832428b45f33864765ac39cdcaab6128b86d")

addappid(290512,0,"7615bc9766b333f365a5c30da616a26215120212dcdfaf11135cdb4577965bf2")
