-- generated by KeySteam
-- update time: 2026-04-14
-- app_name: Rendezvous: Shadows of the Past

addappid(1825480)

addappid(1825481,0,"404dcacad3d1c1b19afb0e473b55f4902d39f7406cd249657cf22316002b8086")
