-- generated by KeySteam
-- update time: 2023-02-20
-- app_name: The Sea-demon

addappid(1825930,0,"099b4ec2b565fcfd32164799ef42aa758b73ac976ed83e38e250a06675640c8f")

addappid(1825931,0,"5daa071853087698677a9b73b568dd59f561f1b59144c3469bc0074142f69e6b")
