-- generated by KeySteam
-- update time: 2025-10-23
-- app_name: Treasure Temples

addappid(1831720,0,"1c2b0af33848fef31242e594942856a006126dda4b0f4664c1389b6d960537d4")

addappid(1831721,0,"066a83369d10889c32460bb63cd9f8cb459fe4007e132436519bb89355ce33f6")
