-- generated by KeySteam
-- update time: 2023-06-07
-- app_name: Erophone Re

addappid(1832740,0,"7589098cbb38870bf4848c604479f1c9e9a7cf9dc46549a7022938c9bd4000d6")

addappid(1832741,0,"b2c9133f2d1656b538e57486ea7ca57b6358b15649c1ac6793fd62bd4af2ca55")

-- DLC: 1/1

addappid(2387520)