-- generated by KeySteam
-- update time: 2022-08-09
-- app_name: Icemaze Cave: Skate Escape

addappid(1834120)

addappid(1834121,0,"90001dd25e30eb9f3a31f6fe6ad8ba1a244100de3849fc26bdf1186c09ed4241")
addappid(1834123,0,"4b9adaee38f96df469a6adaa9fd8b7283f7bd6dd34374774d1b6f0ecb3852c07")
