-- generated by KeySteam
-- update time: 2022-09-08
-- app_name: 赫雷斯的角斗场Ⅱ

addappid(1837230,0,"3e9cfea38b24c3a0491375d0c8b8468adf0ad7099ae7a05d502e3accf635b0c6")

addappid(1837231,0,"03b812d685ba86031cb79bc0599a47ea3d411a70579bfad74d191ed0bafe54a9")
addappid(1951280,0,"10967ec356455cfc03f27c153f9066c642759c11baf56cc00c8ba13e09919e9f")

-- DLC: 1/1

addappid(1951280)