-- generated by KeySteam
-- update time: 2023-05-04
-- app_name: Milk Bottle And Monster Girl

addappid(1839700,0,"ce30543acad39a3904b9be40f7ad1f9d92d597cda23776ff2b5481978ae82c34")

addappid(1839701,0,"74348a75aac6521cdbf475d71465272d67c169e852d7ea44d6cefcbeb576f9f5")
addappid(1852160,0,"9c2b5af7a3f22175396129ba140b9e2c4358353fdabd752b995a3d3e2701e900")

-- DLC: 1/1

addappid(1852160)