-- generated by KeySteam
-- update time: 2017-06-05
-- app_name: CyberLink PowerDirector 15 Ultimate

addappid(501620)

addappid(501621,0,"df0ef8cfb54803422d718beb45304989c839c5b052e50dead2d741de2d47e80c")
