-- generated by KeySteam
-- update time: 2025-12-24
-- app_name: ISEKAI FRONTLINE

addappid(1924140,0,"32f7659f4bb8b64a5d79e385b897220ddaa56bbc090c5904f7f4b6bc46ca5460")

addappid(1924141,0,"bf3ae84c04ed171cde0d22d2539d383938e3dcf0350a52a8b7b111283ad1e563")
addappid(2353770,0,"408a97725b8e34520747bf1c85f71aaa1b32d41aadea7e9f81a1586ec351b148")
addappid(3134170,0,"7f89d233a8bbc805a7a2769b232bab8351bf102eadfbc5db2ac5d631cefecdcd")

-- DLC: 4/4

addappid(2353770)
addappid(2355850)
addappid(2556070)
addappid(3134170)