-- generated by KeySteam
-- update time: 2024-09-12
-- app_name: HOBGOB ～拜托放过我～

addappid(1924990,0,"6077c94faa6f86772b7c46b6dfb215fc7d63b0ac989d7161e2115e9c4b439bbf")

addappid(1924991,0,"7be392b43658bcf98310a1c2c78e442f85e345bc832f551213997a4914fe2179")
