-- generated by KeySteam
-- update time: 2025-11-18
-- app_name: Monument Valley 2

addappid(1927740,0,"86d6ec7b85698d184f5dd5ab5642a88e925207e112687b3bbf1b6bc67e55e0e3")

addappid(1927747,0,"46c8879eb3ab767756128d64c73865baabf28f92ee55743a1271a051ef4cf5e0")
