-- generated by KeySteam
-- update time: 2026-05-20
-- app_name: 月之深渊

addappid(1933000,0,"bfa64a6484a159f9f2fce18c45256ef35cb9699e77cb8409c61a3addcfb50716")

addappid(1933001,0,"053e48598d2860c9d84005844ad2ba7158e805efa30803798f2d4d9c9b6bacc6")
