-- generated by KeySteam
-- update time: 2024-09-02
-- app_name: 魔法书幸存者

addappid(2007530,0,"0d7b85f694a2163cce2a2514233242a4a8d9a02f1c08176f3067e2d11b9f8c41")

addappid(2007531,0,"3b14c44abae033b08e0106204baa1d68b9331044d2ba08a53c3423f79e811871")

-- DLC: 1/1

addappid(2201670)