-- generated by KeySteam
-- update time: 2025-08-22
-- app_name: CuckTales 🐓🌈

addappid(3030240,0,"ede11884f3755e8d86e06078debc79c540532cde9058cbb4bd64b4b7251764e7")

addappid(3030241,0,"d196a0a60d91dc67d747ca27048261548a1c480581b653e09127dec4d395d38b")
