-- generated by KeySteam
-- update time: 2026-04-10
-- app_name: 万象群侠传

addappid(3039500,0,"ba9fa13ae59f0513c7828b2bfade4a7af39a93ccb83eb3a6abfb3029db836621")

addappid(3039501,0,"52933c4abfccfaa0be28a1ff000ed5e5d54d002ce5c79bfa852b1195e226d4bd")
