-- generated by KeySteam
-- update time: 2026-04-23
-- app_name: PUMP IT UP RISE

addappid(2756930,0,"3836584c7f859fbb933f14772c9841ce6459b03a4bd517d33aeb87d68de3e169")

addappid(2756931,0,"654cfb2a808481d61a5d839c4f41eac8c63cb1ecce79750ef671f3f107f4b32b")
addappid(3932571,0,"389018bc4d531a390c6d2ebd9bdba8d84cdf5bb52d5aa6670c43ce6e63d44f0c")

-- DLC: 3/3

addappid(3932570)
addappid(4445930)
addappid(4446060)