-- generated by KeySteam
-- update time: 2020-02-28
-- app_name: The 7th Circle

addappid(832710)

addappid(832711,0,"0b18b8623990183d2355a5e65c9a5a1ebaafab507744def443e5f59d8ee7d94b")
addappid(832712,0,"547fd546fbee26163fef092315ad6c2900443afc1a1486091dc82e4c0d1c98e6")
