-- generated by KeySteam
-- update time: 2026-05-04
-- app_name: 纵火游戏

addappid(2822980,0,"0f937e81687536e7bacc9def6fa66543aa5e38f6ee8f6f77ffd2ff72b4bfea26")

addappid(2822981,0,"bf5fcc89866cb0dfd74367b785755e40f5b0bd488cdc7148b19a8f5e7d42bce6")
