-- generated by KeySteam
-- update time: 2026-02-13
-- app_name: 机核觉醒～露露姆的决意～

addappid(2963320,0,"a91d4290dc2fd6a774ec920296adcdc2f5a24a52c4a8c3877012608e6ea2a08b")

addappid(2963321,0,"dbb90b7c7ecd5724b361edea187cd3a5b2e724fded666f98c0afefc80d6c4cd0")
addappid(2963322,0,"af613c4c15ffe77b8d50f5e1b417e360a036fb1fbd41c627c92ecd3c79e2e38e")
addappid(2963323,0,"49e3ad4d2f562afec3967abb991f6bbfe5a97ef6d3dd6c43d44b19411e531a59")
