-- generated by KeySteam
-- update time: 2026-05-04
-- app_name: World of Warships: Legends

addappid(2964090)

addappid(2964091,0,"81d9633ceae53d1a55f43a061c5d0ecb40e363c50f9fedf4fc176b93c71e2057")

-- DLC: 6/6

addappid(4596240)
addappid(4604950)
addappid(4626910)
addappid(4636090)
addappid(4640340)
addappid(4652620)