-- generated by KeySteam
-- update time: 2020-08-02
-- app_name: 异世界的无厘头生活

addappid(1300160,0,"1fe6846aaa0b5423b6725452e29174610fa2a91de31974a39999b5605e11ba36")

addappid(1300161,0,"478e977e482eac7731ca72f82f4afa71327261f151cefb3ec44f0d9f063965ae")
addappid(1302060,0,"0dbc7a6aa71424a08833db7b0ff2bdaead0a5e2c30b470b65a7b7a5e2bed256e")

-- DLC: 1/1

addappid(1302060)