-- generated by KeySteam
-- update time: 2021-02-08
-- app_name: Singing Iris 鸢之歌

addappid(1315160,0,"a22afef8cc41ef441c290e4634603810345c1a64462fc2938949f8a9f75ab204")

addappid(1315161,0,"dc49ff9946c705f1ce7be6cabe80ac0e06866918ade00f18198db0a55fd479da")
