-- generated by KeySteam
-- update time: 2026-04-16
-- app_name: 甜蜜夏日+

addappid(3830560,0,"565cf7023787a262199a040b7e4b3ee13832358e07d6a094ce84667ad1ee9e58")

addappid(3830561,0,"b7eacfe8f5d3899e4707cdabe74389a525b75fb4020d953f14386f62685aad00")
