-- generated by KeySteam
-- update time: 2025-11-12
-- app_name: Soy Supremacy

addappid(3833120,0,"9d042e048ff1b0640281c62fa80222e2e89265309bab4adfddc9d83cc9e92186")

addappid(3833121,0,"4f177764305ca5a09f17dd5f1c47ee7a68c5b5828dd8c642ab259e89ef736a2a")
