-- generated by KeySteam
-- update time: 2026-03-03
-- app_name: 最终魔王是岳母

addappid(3907210,0,"36bd58e061016369d235d106825e9703915eed6e3555eb88544463a33ea1ca2e")

addappid(3907211,0,"9115b152cbb8ab5b2550874aff099232d39184e43841cfeba8e346774d902229")

-- DLC: 0/1
-- missing DLC: 4347060
