-- generated by KeySteam
-- update time: 2026-04-24
-- app_name: 覆雪之上

addappid(2423760,0,"b447b76fda414386fe29e767b741514ee96a710965aa2d0fd4febcfdcc5978c0")

addappid(2423762,0,"6a6ad2f5d7c96b929831a565ba431d2a56bdfafacf377849f15d89c9b4fa5323")
addappid(4541410,0,"9406147744b828a28acbd9237bdfd43e7f4049aa381831d9c1ec2473f36ca2b6")

-- DLC: 1/1

addappid(4541410)