-- generated by KeySteam
-- update time: 2023-10-20
-- app_name: 对魔忍阿莎姬

addappid(2430160,0,"05462d2a3470a6913bbc4aa87e49645a7e5a5d65701b885b0f36baa28b79b5b7")

addappid(2430161,0,"291f1b09c9e351257963e42a88f4f980528bee404fc171c81828d66e6d40bf83")
