-- generated by KeySteam
-- update time: 2020-02-05
-- app_name: Deponia

addappid(214340,0,"9188562b063bc82bceb2b3df649903421f6011b5c9bb81457b3970065ebdec03")

addappid(214341,0,"c1e5680c3aabd510b1e926d2856e7de33eec5a662753bcff794a8bb91e10073c")
addappid(214342,0,"20b341406d8aec8973a60789f3709a75466001137fb23e605d1f50cc5ca9b2c7")

-- DLC: 1/2
-- missing DLC: 566450

addappid(829510)