-- generated by KeySteam
-- update time: 2026-04-19
-- app_name: Fireboy & Watergirl and Friends

addappid(4401160)

addappid(4401161,0,"fc6292c5f1389e3b4e8e2fe7f504ea83d381695f57fb6ed6880fa96f4c15ba12")
