-- generated by KeySteam
-- update time: 2026-04-10
-- app_name: Sisters in Sin 🔞

addappid(4414250)

addappid(4414251,0,"c83f8b37e4b98049fa4416b945ce8eb674b6be6cf16f35a528b38d3c7b0a2b4e")
addappid(4613200,0,"000948e41fe7357cd12dc809bae2da6c6737260908931277e6b3e4a309dfd3b2")

-- DLC: 1/1

addappid(4613200)