-- generated by KeySteam
-- update time: 2022-10-31
-- app_name: 大魔法师立花

addappid(1981500,0,"beb89eedfc7b2950115f6ab84f41f05124c7f6eaf9a2af9528b79d828ff4ff07")

addappid(1981501,0,"1351a13e56f54cbbdcfef153f1cdf0f9f46e22ee30bab7d8c44f855c1a3ff764")
addappid(1981502,0,"5568e84e3b08854ff9548f123cbd9039491ff2a4191390e4c868f4d3102a7f90")
