-- generated by KeySteam
-- update time: 2024-02-10
-- app_name: Sargasso on Steam

addappid(1989360,0,"a92512c074fb5d629aabe66970c375a57e53966e3416a9f582565b229c9f9753")

addappid(1989361,0,"a87429befb60ea483d7c1d4c4c68e5df5fa8a4480ee9882138e83def7a670d03")
