-- generated by KeySteam
-- update time: 2023-11-23
-- app_name: 催眠典獄長

addappid(1995580,0,"9ad3538c12cc9f99e5bb0fa1236b7feff422bf9739902420eb2141cfa37b4241")

addappid(1995581,0,"df01623b9d0088b31517dde31dd2bc2223372b06c348b7c0d52045e8a3728864")
