-- generated by KeySteam
-- update time: 2026-05-12
-- app_name: 地狱黑杰克 Black Jacket

addappid(3100370,0,"a492fca8370fe3af0e8fc3790a275a3b439fd70f2ea465c58ea84b561763af78")

addappid(3100371,0,"6f520af8fe511bdc08ff85343a4c6976c94bea0213dd877ab716758d5813cb2b")

-- DLC: 1/1

addappid(4635860)