-- generated by KeySteam
-- update time: 2026-04-20
-- app_name: Part-Time Witch

addappid(3108980,0,"237d606b2d8e920a540423311ef913ab6df0cdd541d90a9c852150c1a4df5726")

addappid(3108981,0,"c2012af5efe84f809a8cddfa507e9958d7a85eec5e1ccfde422bf4cd05efdc67")
addappid(4082071,0,"4d2fe166db312a59ba66820482f86cefe9e7d783f1103aceb74109a83e6b7b20")

-- DLC: 1/3
-- missing DLC: 4082060, 4082080

addappid(4082070)