-- generated by KeySteam
-- update time: 2025-01-23
-- app_name: Townopolis

addappid(462730)

addappid(462731,0,"f81a24043040e355c1e869d506d399d220ebeb28c608e3f6ad6bf55aaeb77c14")
addappid(462732,0,"830bb81b787c3f452d960e474908da77978dc3bda45d7225f6995c10cf4c9195")
