-- generated by KeySteam
-- update time: 2025-01-23
-- app_name: Romopolis

addappid(471170)

addappid(471171,0,"5b13a87525355302c9c2fa2fec3eee4c523266e735c62c79d08868d2bb34d09c")
addappid(471172,0,"3beee6f362f9671a01e99f6acbfdcf9e7a24e7d94996d9962138bed570baeba4")
