-- generated by KeySteam
-- update time: 2026-04-09
-- app_name: Hyperborea: Hornysolation

addappid(4102950,0,"322a0b0b341d9c834eb4182ce2952b80d5637fe15dc9eb126bd8d1d433a4aac7")

addappid(4102951,0,"32e298f0daad14231d9fc898a5d3de199a0c4583ce8d95df7d59ec8ca68075d3")

-- DLC: 0/1
-- missing DLC: 4403500
