-- generated by KeySteam
-- update time: 2026-02-10
-- app_name: Ultimate Sugar Crush! Brick Breaker Desire

addappid(4113250,0,"158fda150d63e496b1e929a6ffbf91c16af9256dbbd9ae8766f29439d70688e9")

addappid(4113251,0,"5c24a00fc8006855dc5c9fa785076ff176dfb6a0e98a76f731dc994d9a3ad92b")
addappid(4113253,0,"702300b32e978ef08d8ec8954560363a7009784aab707d5f7177630672eeef7b")

-- DLC: 1/1

addappid(4331600)