-- generated by KeySteam
-- update time: 2026-04-03
-- app_name: The Riftbreaker - Dedicated Server

addappid(4114030)

addappid(1004,0,"f21faa4f29ecee9d192fc1784d1701376eb87e13521824ceaf0116b10c558a81")
addappid(4114031,0,"b492b04538a49185aeb0f8408ed51c57f6d3667a026b8817b93462157dc02a0f")
