-- generated by KeySteam
-- update time: 2025-10-16
-- app_name: 荒原疗者 (Wildmender)

addappid(1599330,0,"57de6362f3d76964ce6f68980756db91c1097e6d1887cd082156e4da619334ea")

addappid(1599331,0,"afd9a47ff2961d2300f050adb60d8518347475523c6708a9208f349156cc6835")

-- DLC: 2/2

addappid(2540280)
addappid(2540290)