-- generated by KeySteam
-- update time: 2024-02-28
-- app_name: 零号生命体

addappid(1848270,0,"e391ea30383b6f9f02f61715b1ad9c182d2887fc41fcfe27c11f8c8ed4f67540")

addappid(1848271,0,"062315b3feb470d0344e646cb11ea7f2b2a83b77889c5e18376730101f837449")
