-- generated by KeySteam
-- update time: 2024-04-18
-- app_name: CODE: PANDORA

addappid(1850520,0,"37531ceaee5aba8fd91a4b6224d892dbce374844e023af674179f11b655b6ac1")

addappid(1850521,0,"abd0868a11d90a26b0911ee489f6ff053d74b61b88c76c4093db4ab3ae05bc30")
addappid(2374520,0,"a650eb9e3ba534676010a52c5d621c0c25f9c89607421dd3740fa5b2587223ac")

-- DLC: 1/1

addappid(2374520)