-- generated by KeySteam
-- update time: 2022-07-17
-- app_name: 恶魔调酒师

addappid(1854250,0,"a21e3cf04288d9d26ba3085530c968347b47e7b8f2e033b13bb2030d78a7860d")

addappid(1854251,0,"2f47694e5fe8e10fee5b3f0979c7086bc2745d9b27ed96813ff5a28e39b9f388")
