-- generated by KeySteam
-- update time: 2023-01-31
-- app_name: Planet TD

addappid(1859490,0,"26326ea87d28ee5f6771233eea0f07b36298d49b3597336992d04177a8e4c1e1")

addappid(1859491,0,"7e69a6d17b5f851531a5c3b7a8b2fa4f70b7881a136db11e06b545c627e668df")
