-- generated by KeySteam
-- update time: 2026-03-16
-- app_name: DanceXR

addappid(1905510)

addappid(1905511,0,"079f4d3fd40c87f7df89090998e68b65ec12423b05c6a306bbf87428f4c54463")
addappid(2063770,0,"bac5c6110f741dc536cc17e52ef0673126c36e52d7efed6b6c464852ef1ffc1f")
addappid(3801770,0,"8ffde09468aca4791095b3397aede679564d31f4662b7f9881979d34c5b5f0a5")

-- DLC: 2/3
-- missing DLC: 2819100

addappid(2063770)
addappid(3801770)