-- generated by KeySteam
-- update time: 2025-10-06
-- app_name: 残存记录

addappid(1916310,0,"6e6091f419d1bdefbdb6802c32b53bf8546f37187553dbce55e202f12cf7bf2c")

addappid(1916311,0,"c15fc1641b06961cce20b338388106482b2b58047fc4a139aa1c75fe574ef8f6")
addappid(2781132,0,"1e8faa0235acd7356e9203785cc26ecfb94ec831a665ad10224f316f3a514ca8")

-- DLC: 1/1

addappid(2781130)