-- generated by KeySteam
-- update time: 2023-05-04
-- app_name: Milk Bottle And Monster Girl 2

addappid(1917560,0,"43244d17768745c4e0b24f79148b71f7186b25346c26cc9bc090fc1c533ec53d")

addappid(1917561,0,"2dfd79681913506ff98511beae90801a317291befa299c635c2da259357a6a67")
addappid(1928400,0,"d37a4b6a35897296405a8a9b57fe9daa22a744181bc0a0057ea2a25f15cbe4d8")

-- DLC: 1/1

addappid(1928400)