-- generated by KeySteam
-- update time: 2025-01-23
-- app_name: Megapolis

addappid(485080)

addappid(485081,0,"d3494f16f45374bb6c950b106e192702200bdb2e61241dfdd7e57db48fa700a4")
addappid(485082,0,"ff253fdb95bbf368909739c2c333d52556d53a944d8bbd9ba4ad467a065baf70")
