-- generated by KeySteam
-- update time: 2022-11-22
-- app_name: Wild Romance

addappid(493450)

addappid(493451,0,"49f2912788a43146115edcc52eeda45feb3dae00622b58440c5671b6757dcae8")
addappid(493452,0,"0c25bd75f360c45d0c2083b1d5feeeed103f2633f84185a3920784ff09ab34df")
