-- generated by KeySteam
-- update time: 2026-05-10
-- app_name: Black Hole Fishing

addappid(3667390,0,"7463da0ff05226306c827f8cd6f6e74bdbfc99e6efd398716279753b5bdfcbf7")

addappid(3667391,0,"de2bcd10a6f1e71570a2dc91eb39fd8087b4f17b4affe4a53b8e6bfd53b9d661")
