-- generated by KeySteam
-- update time: 2025-12-03
-- app_name: 堕落女忍 ~寝取隐村~

addappid(3670880,0,"47ee063ad532cba203e87c936cf9f9cacd9dd1801de9a8ffa33c1c7306b8563c")

addappid(3670881,0,"7d42e32fc92274cc4ddcf1c43efe15fc9abb1019b402a6a62423db4ac37324ad")
