-- generated by KeySteam
-- update time: 2022-11-23
-- app_name: 收容：秘密档案

addappid(1718130,0,"6d6291bb0a0b29aaac7afacd744832257f299db0d250feeb652e9b112d97dda9")

addappid(1718132,0,"20b7e1fba1d9d2276149ef9e61f90a2e9e729876c094bf8536c3f03b01819601")
