-- generated by KeySteam
-- update time: 2019-10-28
-- app_name: Undertale

addappid(391540,0,"fb8cdff25bb9ba56eb73d10f640db1d2a7fa8846ef6be025bb87186e8bcc53c9")

addappid(391541,0,"b416ce2b64256c530f83775eef790b171047ce48c3795077ebcfd83f9c627cab")
