-- generated by KeySteam
-- update time: 2026-03-31
-- app_name: Naev

addappid(598530)

addappid(598532,0,"bd0eae8dd43e8e356e8c4f253f5da16965d38b4df015bc2e58475b5554b26806")
addappid(598534,0,"47ed43ee392e7f3b3b129369c2e271f8a9897ce4a185725d15a6147f7746ad7f")
