-- generated by KeySteam
-- update time: 2026-04-06
-- app_name: Battle for Wesnoth

addappid(599390)

addappid(599391,0,"453a189f401660e3b4c3b3174b8c10c4aed809aebc76dc434a39d994bff63722")
addappid(599393,0,"33c5ef8f64bef9299cc1222e55860d99a99f4a15e166c328984318def3be4c55")
