-- generated by KeySteam
-- update time: 2026-04-06
-- app_name: Knockout 2: Wrath of the Karen

addappid(2349350)

addappid(2349351,0,"5422a71f779b92fe353681d0a18cd27b089c10c9371935aa80487f0e4448096d")
