-- generated by KeySteam
-- update time: 2024-04-01
-- app_name: Hot And Lovely ：Suger

addappid(2732490,0,"294ec350b146c177c1c2d50b5fbad40a92407d9bb5a0145b6f00f01a37a165f4")

addtoken(2732490,"14182339517676421723")

addappid(2732491,0,"de78be8d975469eb162ebf657675a2ed7a9ece5e7dc9157f657808ae5966faa4")
addappid(2819250,0,"3b13742aeffc30a2eea29c953d542989c575a494d217a4ce3da6ac3f553b85ff")
