-- generated by KeySteam
-- update time: 2026-05-01
-- app_name: 群女乱滩齐斗艳：处男撒香引爆春潮海滩

addappid(3654030,0,"946c6e70e90039553d19f20af5632cf5859e6dfeb5ec180568686a39ba192464")

addappid(3654032,0,"497c48a3ac910b1efa77c66ca27668c9e543fc186c5517bd7db958fd59ac4540")
addappid(4618180,0,"4109158ff7250a8d3eacf7030797f8d4d3e8e0f28cc4da171b65cbd59631d92c")

-- DLC: 1/1

addappid(4618180)