-- generated by KeySteam
-- update time: 2025-10-14
-- app_name: Nakara

addappid(4083770,0,"a925b87665656af8eb6152694bd07664660817b02ecf8d0884c9211ccdcd357f")

addappid(4083771,0,"7a84d220eea6793d25bfc3912b18f43a0f577b99bbda1859e5c332d3b1cf5f19")
