-- generated by KeySteam
-- update time: 2023-10-05
-- app_name: 墙世界

addappid(2187290,0,"3e693781e3c44bb2cb029a9404b25cadaf2ec59f7781745cfd3f298fd2b81526")

addappid(2187291,0,"cb01cb5f16254236ce96818ecc2102c55ceb5aa5a6163fb45bd3a6687308bd78")
addappid(2474861,0,"894ebeb3858c0eed31b480870954e01826daaef5e6df90a1aaf3dbe1393633cf")

-- DLC: 1/1

addappid(2474860)