-- generated by KeySteam
-- update time: 2025-12-09
-- app_name: 传说法师2

addappid(2193540,0,"2269c0cb2840f90262978a2eca978b358ac3d5a4e3d1e78ef2a973f29b0904a7")

addappid(2193541,0,"0b38693b47350ed1df704c576d67dd2d05ce6e286543e940c52a95a6f7b3b812")
