-- generated by KeySteam
-- update time: 2026-05-08
-- app_name: 战术扫雷：肉鸽Plus

addappid(3161400,0,"913bb06365730d67f5543f7b62b4990edb7a327aa43afb49bfb941b1d5876ccc")

addappid(3161402,0,"7069d2ffdd7957f267e862396d6792fb4eb7619a3a473e142ef0d5427cb67aa8")
