-- generated by KeySteam
-- update time: 2024-08-22
-- app_name: Tokyo College Girls

addappid(3171000,0,"4da752a9dd944aa4a4b031811d5db76e1c403575d999d1c4dd44469e0b5eb8f5")

addappid(3171001,0,"5b0f4dfd477c8f0e812932181ad19b1b9c7bd5b74186361dfcf8aa2ea9dbf783")
