-- generated by KeySteam
-- update time: 2025-01-15
-- app_name: 合约女友的一日体验:凯洛与嘉米

addappid(3172190,0,"5d6423ce68f7b436d5328e51708fe828332235e8bee751f33d30d6c2393e8cf8")

addtoken(3172190,"172770667116382702")

addappid(3172191,0,"a9dfb8d7b50461e7c42960f5d500bee69024f88c9af6af83cadcc477b270e6b2")
