-- generated by KeySteam
-- update time: 2026-05-23
-- app_name: 冬日生存工程

addappid(3174500,0,"29d34200b9f9d8b30e001d9f9cc2583c76281b6e6ca1fbe928f0734e3bfb060c")

addappid(3174501,0,"894e98e4349255d43750361c31f3066ad47f6cee4e1f8aa990f94aa869bea868")
