-- generated by KeySteam
-- update time: 2026-04-15
-- app_name: 种呱得呱 Rana Card

addappid(3177890,0,"850d157e5a34ec845c64d82b2de7ded5062b86a7d612426cd0948b1e068c087b")

addappid(3177891,0,"344bcf8bc7e6615ce2520bdf84cbf5ad3430bc44909cef5998141e64fa3474e7")
