-- generated by KeySteam
-- update time: 2026-04-08
-- app_name: 饲养染的30 DAYS

addappid(4045190,0,"2cb0bcfa42a9891f643826bdcfed79c80e93e548c2f4b362d58dc0c0490fff3e")

addappid(4045191,0,"c55ca69adede209d7859a4d01f316fc048893ff82a67484e10117c026884c851")
