-- generated by KeySteam
-- update time: 2026-02-27
-- app_name: 虚构悖论：第一章

addappid(4058160,0,"e6b2553ed36bc9236d80a3f86fb8d5b38c6087a7e1b070556ab54ecdc8635122")

addappid(4058161,0,"49187c621917ca47dab24512677f8ee2445bc1c8ca8aa36fec0f5542b38173e8")
