-- generated by KeySteam
-- update time: 2023-11-06
-- app_name: 黑兽2‧改

addappid(2544760,0,"9bade15af4e968d19e73008366d7d7a6ac33098709874706d832bf2364c30a78")

addappid(2544761,0,"682c7601460a705d5841320d68100eb63eb6f0d4eb0259069fafbbad144ca4fb")
