-- generated by KeySteam
-- update time: 2022-10-19
-- app_name: 幻塔

addappid(2147450,0,"a488813825c93f935d7e00df55cf1cd3c21b97a3db0c829d0e820e4fcb07d09b")

addappid(2147451,0,"18f122639470c2a6103dd8432ca0507510cafd4ec93f25296de673fe8d630220")
