-- generated by KeySteam
-- update time: 2022-11-11
-- app_name: Yokai's Wish

addappid(2151700,0,"45b5dccb98fb3b6d55bcbd51eed6737ee49a59740ba63ae2c8414f762872eb9f")

addappid(2151701,0,"a95706090534e6469528ecf5bb762a89c3b771716ae52d059d3f3adf09f6a83f")
addappid(2201120,0,"97f1173aa1b0190e345b7a5afc4e0b0a24348174a6bd71d46625e37c6f254278")

-- DLC: 1/1

addappid(2201120)