-- generated by KeySteam
-- update time: 2026-05-15
-- app_name: 橡木塔

addappid(3400960)

addappid(3400961,0,"9975b9c771b76745869399d9f3b7be6e3ceb769e83eb21ce6cb682dc4f614cf6")

-- DLC: 1/1

addappid(4596710)