-- generated by KeySteam
-- update time: 2026-05-05
-- app_name: Dead as Disco

addappid(3404260,0,"9debe6a2ea11163149dace65276f9373f519138782918176a982b8e7c3428fab")

addappid(3404261,0,"973bb66b7d1dcddebad49a40c9bad583fb090e27d3df4fc57fea8b9732ce6680")
