-- generated by KeySteam
-- update time: 2026-05-23
-- app_name: 拉斯维加斯模拟器

addappid(3412160,0,"12431f2436b0a51bb3819ec8addfbaa33d752caa495a3b91748ae6e266e7b487")

addappid(3412161,0,"e13415101c7f16966fbeb09c1666b9b664b1f8587de1b79e5ff93f37a85f1b00")
addappid(4579370,0,"85efbaa380949c2b7ab1edfde70b05ca834e47fe581784d03b33f6f2582326ac")

-- DLC: 1/1

addappid(4579370)