-- generated by KeySteam
-- update time: 2025-11-05
-- app_name: 夺～出售伴侣~

addappid(3922750,0,"a44db7fcaaaab6aeeb774000e40acfc414ba1242b1b4efa9198ee4199ab0f71d")

addappid(3922751,0,"39a1eab583e2303faed0cd0a7811d0cc8164ea7b65c0c01106a49e4072e2d05a")
addappid(3922752,0,"73a0e91e05f67e7f86d97d65769f4bba3306f046a1470139bb63ea01f2500930")
