-- generated by KeySteam
-- update time: 2026-01-24
-- app_name: Holo ADV: SakuraSingularity.exe

addappid(3923980)

addappid(3923981,0,"9744a1e5daf35ee3201ba42a5d28c9c9bab22135cc98efc1fe663e66121394cd")
