-- generated by KeySteam
-- update time: 2024-06-14
-- app_name: 远星都市27λ

addappid(2442410,0,"8dcd230340998a4678f53b11ea77c14d64431db27aa845612553ce755500ad5f")

addappid(2442411,0,"aa7c1ceb827fc6c0ab562c94f3c597b72668e12af60bf45a92c8462d70810054")
