-- generated by KeySteam
-- update time: 2025-09-23
-- app_name: My Classmate is AV Actress

addappid(3063290,0,"3444a581156c5303715f0cf6c99ae9d4520b0006abc7b89b4e2f1ccb085a8e4d")

addappid(3063291,0,"c63caa02484f0c39b3ee396cbc4befcccdaac5f291e3204792d96f556226ed20")
