-- generated by KeySteam
-- update time: 2026-02-19
-- app_name: Labyrinth of Touhou Tri -The Dreaming Girls & The Mysterious Orbs-

addappid(3067930)

addappid(3067931,0,"d51838228b6837025cc0b5d11a1b27f71400ffe89bd28efa52111578809126c7")
