-- generated by KeySteam
-- update time: 2026-05-24
-- app_name: Serpent's Gaze

addappid(3069050,0,"ea5dc03918cd687633a3fef736ac01ded864f712e9c8af044df00d2aea3c1632")

addappid(3069051,0,"bcd67a9fc64765698b84b934147d5db07fdd5054fa018138164ac0906a634d18")
