-- generated by KeySteam
-- update time: 2024-07-29
-- app_name: 3073380

addappid(3073380)

addtoken(3073380,"1190552604195476929")

addappid(3073381,0,"bfb46f5c034145d6c708eb3e3fbe3e3998f4dec4910decc84a454116a4b566b0")
