-- generated by KeySteam
-- update time: 2026-05-19
-- app_name: 深岩银河：异动核心

addappid(2605790,0,"1af9a5e28de370e8e846346aaed0eff5816e663fade79831061acb4cf8de8e4d")

addappid(2605791,0,"7308ffc34728d2db852dc47175323866ad2e9ba1d12f6fba302c8f768bc7bce2")

-- DLC: 1/1

addappid(4216130)