-- generated by KeySteam
-- update time: 2025-10-01
-- app_name: NUKITASHI 2

addappid(2614070,0,"bc03b2ad27b1e0194333365ebee47cc2f09ecb2949aab4b606d48f73e3941f4f")

addappid(2614071,0,"85b2e14de3f99250e09830257b8ce9b7344187e52cacf34930d5c218667b6b94")
addappid(3936700,0,"70f7f2a45395070764fa6850f0fcde1cba82ee127a0c2bb9f60eb1f7109a9c52")

-- DLC: 1/1

addappid(3936700)