-- generated by KeySteam
-- update time: 2025-09-02
-- app_name: Delivery Days

addappid(3860730,0,"4fcbd2c7cf8a608ce09b3a51f4529cb5f826a55c3c8783e5db96d6eca770bed4")

addappid(3860731,0,"31e57ef23a85f7247f452a3362e3457c12fa5b81a391e8cbda1a0ab43db81fb5")
