-- generated by KeySteam
-- update time: 2026-02-04
-- app_name: 大学助教生活

addappid(3867010,0,"4d6057f9977ade6b33e320d947a6ef500519d826d03e3c9df0fa93753768fc47")

addappid(3867011,0,"f2a71e12f67137d24ca1170e140e66341ff64d4c3aa2bd7de61687817f3b25f4")
