-- generated by KeySteam
-- update time: 2026-01-28
-- app_name: Five Nights at Dream's​

addappid(3874470,0,"8e3289c6fec3f54fa423e2f02ab4a6ba79bb12da1f3b678557f8846b0e2f0472")

addappid(3874471,0,"e15e7006cc02f40cb249c446a2caeb37fe0494ee43565becba1bb1225156fd5f")
