-- generated by KeySteam
-- update time: 2026-04-16
-- app_name: 面包日记

addappid(3755320,0,"4234dedaa6ba89d393ae00e771ff251a7eebe432cfc8c2ef0f610b7c3d6b1e7d")

addappid(3755328,0,"35ea6296aaea8d125c82702bb9da38c6dbb6ffeffbb28c85bdd9d7b2860439ca")
addappid(3755329,0,"7869ab30fea9ae95947be156c91fb23ac06b73e1261ff46acdd00192b91a88f1")
