-- generated by KeySteam
-- update time: 2025-12-19
-- app_name: 炼金术士的秘药

addappid(3759330,0,"c2806667548a62a679938748f43c10a98f806c18f88b5c9de3f6582127b2e435")

addappid(3759331,0,"fa2ab37c28a6aebd67e73624e23468c3a60efaf64319e2fe49c365d1c555b228")
