-- generated by KeySteam
-- update time: 2026-04-20
-- app_name: 掘地求狗

addappid(4244510,0,"956c9391ad465b7ec5a1594b981371d733a6b3efa0a2a2281c73c592de99e91d")

addappid(4244511,0,"f51cc41519216d4769c3d179a9ca0908c96de20df61c3a4b5e461f27e8a75dec")

-- DLC: 1/1

addappid(4327880)