-- generated by KeySteam
-- update time: 2026-03-19
-- app_name: 邂逅酒吧2

addappid(4249370,0,"e5496e36e9a29bcab7525787a3fca7fd7aceda14d87ee0b8cf8ebaaf43815f68")

addappid(4249371,0,"027f81dec96a77751f76faa2d5eb91810710354af3147bbe322c487afdbc357b")
