-- generated by KeySteam
-- update time: 2026-03-11
-- app_name: 回乡后，有超可爱幽灵在我家!?

addappid(4250010,0,"2cddb147d690b72c47b9fa3354092c20a214468a7be79f9d5e4d751eb15e3c0a")

addappid(4250011,0,"62ad973153b2d6acb9435007896bf23c735604b099592a3500fa93d7f2358f04")
