-- generated by KeySteam
-- update time: 2026-04-07
-- app_name: 深 四目朝生-阴阳之巫女-

addappid(2948080,0,"779154bf2d98914244dbe6319ea5b64486445b06d7aa108b85de0ae5da0eb357")

addappid(2948081,0,"06417b8e4ca5e43117be17cac4d336f3b9c82b555acbd1f4a72eb53c999af12f")
