-- generated by KeySteam
-- update time: 2025-04-01
-- app_name: Her Last Piece

addappid(3042250,0,"0fce0d8a06356065871603f668e407a8968d9ed1f2216462a057c2435482e6bf")

addappid(3042251,0,"644b0beed3b491a692a4f916696db56fc45bc2c829e84e4ff6ffe7bba5803906")
addappid(3613180,0,"54cc27d5757d0b26c4ddf07999e7727db6f14ef7eaa71ae652e6ca0440834255")

-- DLC: 1/1

addappid(3613180)