-- generated by KeySteam
-- update time: 2025-08-12
-- app_name: 请成为最能干的VTuber吧！

addappid(3044740,0,"002d6b01936631994440387fc0ce48d9dd44fae13b1a84330c4d0e64ed653939")

addappid(3044741,0,"7fe1736dcd0fdddc507d4692a06a7610a694c6875eeeca84ae09158c2ddf2165")
addappid(3780671,0,"2a16fbc9fcdc2b7b9070a75c785401d3d2c93f751ac3c16a2fb1c649d67a0ad1")

-- DLC: 1/1

addappid(3780670)