-- generated by KeySteam
-- update time: 2024-06-20
-- app_name: 玉剑倾城

addappid(3058160)

addtoken(3058160,"6398728709254883166")

addappid(3058161,0,"446b69e6e15c69fab681f0d1e1cce7b70ea9d32cdb8e2dba59fbd1aa89f2bb90")
