-- generated by KeySteam
-- update time: 2026-04-22
-- app_name: SimplePlanes 2

addappid(2840470)

addappid(2840471,0,"1849882c014676488fe6b3e4ac5a33a61ee95e803353a176bd37243396d1d137")
addappid(2840472,0,"8684d95bf48a00217eec9db68b71fafb1f80c2871f9a882c5f10e3f8e4550b52")
