-- generated by KeySteam
-- update time: 2026-03-20
-- app_name: 尸姬之梦

addappid(2842800,0,"9724c7694b935986ddf5f3c2f439475ba20d3b26ae14e102be0515f25ef2d05a")

addappid(2842801,0,"ff61e4f261e08ac99710b14666f720fdc9a3e577d65e65654bc60ca5f25482c7")
