-- generated by KeySteam
-- update time: 2023-01-18
-- app_name: 隐秘的角落 试玩版

addappid(2072050)

addtoken(2072050,"321207004072348873")

addappid(2072051,0,"85fbfdf56a2114394220a47067617ad3cda1c6f0c961dacbc5907f5d55690b2d")
