-- generated by KeySteam
-- update time: 2024-05-16
-- app_name: 闪耀滑雪场物语 (Shiny Ski Resort)

addappid(2072170,0,"c784675071840f78633c519d5a2964bc5c992c482b0be97ddcf2362b1b2b2d6c")

addappid(2072171,0,"777aa0a3ade3f5cb749a6df54f52ad3ab68f436c21b7f2cce64a2d48a07167fa")
