-- generated by KeySteam
-- update time: 2025-04-11
-- app_name: 电车之狼

addappid(3521860,0,"736de9302b25e434924cd87cbc2501af410ba6415583ec3a280a6be63a3cd25e")

addappid(3521861,0,"ad72b1afd0ffbd442ab1437a9c0874efd5d6c08e1bf9c5920c79ee839f251af2")
