-- generated by KeySteam
-- update time: 2026-05-01
-- app_name: 万物皆可蟹：动物进化 Roguelite | Everything is Crab

addappid(3526710)

addappid(3526711,0,"ed639283b231e8c9cf3f2809bafb053eca94f9edd0d68f2678b1b9ecbc100e83")

-- DLC: 1/1

addappid(4540950)