-- generated by KeySteam
-- update time: 2025-11-14
-- app_name: 靠辅助魔法建立的后宫无双生活

addappid(4063960,0,"5c744fae2452e1ca644d2f7e414ea0f0c4ec199869d1117b31f8edd22728b354")

addappid(4063961,0,"25ff0b26058d82b89250a0c785c3b548302bd240fdea1251f8de2691713b5eaa")
