-- generated by KeySteam
-- update time: 2026-05-18
-- app_name: 矮人吞山

addappid(4078200)

addappid(4078201,0,"92bb914bf6864cd05a4afd5bd5a3c9e478625d1bd308f34d2bc585d1a08761b9")

-- DLC: 1/1

addappid(4732170)