-- generated by KeySteam
-- update time: 2026-05-14
-- app_name: 权力的游戏 : 国王大道

addappid(4214820)

addappid(4214821,0,"339d48020dcdfbcfecb33e1964ed1fd5cdcae4c987c73aac100c67f9e68badd5")
addappid(4214822,0,"1a20190cd79819bfdca356676eb64166d3068c239ffcd298c1afb664edfd56ea")
