-- generated by KeySteam
-- update time: 2026-05-11
-- app_name: Outbound / 拾光旅人

addappid(2681030)

addappid(2681031,0,"feac3f781af42ac4e65cdb05e24f482c33e5660d23b377e86d744be6cc53a4bd")

-- DLC: 1/1

addappid(4148860)