-- generated by KeySteam
-- update time: 2026-04-15
-- app_name: 灭绝之日

addappid(2682380,0,"fd7a2f6654630665f63fac58df60ab4817c4cf621f6f76dc950e76010dc88123")

addappid(2682381,0,"60506581f93e172482cf28b0cbbbcce9eeb0ad428b0da9ed42ff1c31dd412143")
