-- generated by KeySteam
-- update time: 2023-11-07
-- app_name: Gentle Female Boss 温柔女上司

addappid(2687080,0,"8b1cbc7a07c264b0a21ea725dc1fff66109ad828f4d3cc1450b85d89977cbf7b")

addappid(2687081,0,"b479432a97647e4903f6f450d78d9cf6808f60eb3da0ddbdb14b6444d4d9eb66")
