-- generated by KeySteam
-- update time: 2025-07-09
-- app_name: EmyLiveShow: Dragon & Mistresses Tale

addappid(2695290,0,"fbe3baa4f4749eb5eb5fea9529e2e669f7fde9bc0522109f5cf8de4fb2daf480")

addappid(2695291,0,"771f6e04d448bcf77efc4852c052a5eb58440a582b64264d2dbd7b6f31ee3b33")
