-- generated by KeySteam
-- update time: 2024-06-30
-- app_name: Miss Neko: Pirates

addappid(2695270,0,"cd94808e03698783182e328e87c794878e6e184ed3cf1dcef6c9288b8f172d2b")

addappid(2695271,0,"2a96571ddde236385169574854f8eb25a15a715b5da5674059492fe0a7ae57cd")
addappid(2824300,0,"ac55798aaf5fb0397a7f0f5a16c3602b751cd7ecce5767dae51f55263d099d14")

-- DLC: 1/1

addappid(2824300)