-- generated by KeySteam
-- update time: 2026-03-09
-- app_name: Souper Game

addappid(3181790,0,"0e331b8c7693c922de90fec8ddc7311c899c30a19c4dbe7d18e263d367796076")

addappid(3181791,0,"0bea736e5c7869a39e125bd41f1172b2a858332d4e06dc1c8149f848e479f7f2")

-- DLC: 0/2
-- missing DLC: 4312290, 4312300
