-- generated by KeySteam
-- update time: 2026-05-14
-- app_name: 猫岛雨香

addappid(3181890)

addappid(3181891,0,"73c33e50ee3e75dc886c962e187587ae98da48b5a4ddeaf1e3017577422b81fe")
addappid(4334942,0,"a777847ab60d139b8ecd7631fb06d26552ec4689be5ffbf21fa6198745434d14")

-- DLC: 1/3
-- missing DLC: 4655150, 4655160

addappid(4334940)