-- generated by KeySteam
-- update time: 2026-05-06
-- app_name: Formula Legends

addappid(3194360,0,"3781566b837b2f6018dc45d577f6ff11f140c795ca80a887b663da1c7028effd")

addappid(3194361,0,"2eab901f3297c0706ad8606e564f7913bf97b561233741ca20f0de137d4142f3")

-- DLC: 8/8

addappid(4060830)
addappid(4060840)
addappid(4143900)
addappid(4143910)
addappid(4143920)
addappid(4216430)
addappid(4222670)
addappid(4362310)