-- generated by KeySteam
-- update time: 2026-05-21
-- app_name: 仙之气

addappid(3196590)

addappid(3196591,0,"4b721e49a4a33f4c0d8801bb4b87aa48b5358681351471279b1278d44c437b16")

-- DLC: 1/1

addappid(3773660)