-- generated by KeySteam
-- update time: 2024-10-29
-- app_name: 血族少女也能当圣骑士吗

addappid(3084580,0,"7eb107a284c2c173cb0e8692cb2c466adf186b809d8f7329ad63bad9686b5286")

addappid(3084581,0,"a6cde9adf52514d9a1afbf5bb6539a917636eef9e1bf642f67c03fc73290ad7f")
