-- generated by KeySteam
-- update time: 2018-04-16
-- app_name: Anime girl Or Bottle?

addappid(785110,0,"82fc631000f8b927799f62a7a9108963b7b086421436fa92e2ba936d535e282a")

addappid(785111,0,"c22520f7099732b40c003bc934d2d6796e87c9b327455066f377f535ed9426df")

-- DLC: 1/1

addappid(836090)