-- generated by KeySteam
-- update time: 2025-10-03
-- app_name: 霓虹深渊

addappid(788100,0,"64fbc7049d7e131e1a71f881865c05ec26774c151ee2bc2b10c2c70162740b8b")

addappid(788101,0,"1524d54ee8d4105840022012751ba42ac9d631c069c91f661f0869a5801a146e")

-- DLC: 3/3

addappid(1262000)
addappid(1518790)
addappid(1851340)