-- generated by KeySteam
-- update time: 2020-06-09
-- app_name: Lair of the Clockwork God

addappid(1060600,0,"43d3abd63c822a7985a911c1975fb21d44b74f7ee2dcda819aac6e9ebc41aa5a")

addappid(1060601,0,"dac5ea2cc8ac07ad58690798d2ace6297c2d01d7b429c8957f5ba68c68ab406b")
