-- generated by KeySteam
-- update time: 2025-11-02
-- app_name: 龙族至宝：广茂之绿 (Golden Treasure: The Great Green)

addappid(1065100)

addappid(1065101,0,"a1c5b0a512a02842c121d5046ecbe638c69185c05076d013ee2c097af144b30f")
addappid(1105880,0,"afd29b7dc24613c9b9e0f57f0ccffd90fe9bc1cede26bf0b8b3f2690574ec1d1")
