-- generated by KeySteam
-- update time: 2024-06-09
-- app_name: Graduated

addappid(1070260,0,"6f0622159a48869e2ddae4ec94ee3c9e8541f6888ba60accf010cab82e5fa582")

addtoken(1070260,"15659743433180896738")

addappid(1070261,0,"84d0609153540e78f3a7291fd18cebe1ddcbe1ee7623cf4739e6ede2a70e64f5")
