-- generated by KeySteam
-- update time: 2020-03-20
-- app_name: Cossanox

addappid(1072280)

addappid(1072281,0,"fb1cbac5b7ae398dd7a0534d0cfd97c81efa550fb982a81df1a485efcf44ab22")
addappid(1072283,0,"ad9260eb573c5ed799d679ad8e7980f5cd5d23ae7ed62f609fcb6c3e9043c983")
addappid(1072285,0,"9e0c2854534b61abdbf1066713cdbf50712f9edab55e3ed698a9fca7a89ed01d")
