-- generated by KeySteam
-- update time: 2023-06-22
-- app_name: Adorable Witch5 : lingering

addappid(2271980,0,"eae14a66f41a547c2ab01b5b9ba71c2da9859b2b21730e3284b82f52ff7e39ae")

addtoken(2271980,"8333188460037508187")

addappid(2271981,0,"8692333f5771350972c8e620786ac563ec87778dcbbfc4713208da455a609a4f")
addappid(2277580,0,"bcb5d2ce8545849f62f502601fae2ef6306debca7c66e09ab68a1f09ec1b0a7c")
