-- generated by KeySteam
-- update time: 2023-01-29
-- app_name: Kiss Effect

addappid(2288480,0,"6cf366576b96a4c06d9973f48dd37983152a07b8d91d74e57ee168d0ce41a67f")

addappid(2288481,0,"7dc6ce02ace230185492be138e8c98d53446f2f9bfb781c5737bdfc89ee7925c")
addappid(2295620,0,"5edf689cb856d908818edd6a41f17bc216559f97216c13f715eb2a9869daef03")

-- DLC: 1/1

addappid(2295620)