-- generated by KeySteam
-- update time: 2026-02-12
-- app_name: 女尊异界冒险谭

addappid(3841010,0,"ec5b5a1efd4d6daffc690734953d7f2f2265713a4b9abaa8e6d373d373619dd5")

addappid(3841011,0,"bb2d716ae4af9f55d98721d6511cf0e70a48d9d1fcb90beb547a3e062c8c9d12")
addappid(3841012,0,"aaa2a635c962b3ef7e9b0bf6a474a6c2fdf2dee48f4315452f7427eecb9c1687")
addappid(3841013,0,"d57e86712c8fe2a165e79271eb161fa5fa9080eb674b9491e2b641f7dba76aa0")
