-- generated by KeySteam
-- update time: 2025-10-31
-- app_name: HH TRAP~改变常识的陷阱~

addappid(3857950,0,"c4830f47cb3ddc8e93cd8480ed9b6746fa7f3c44e171e6d92c26fc8083bcda0b")

addappid(3857951,0,"c429e31acb8c3f1d7e43644954a2afe5493af021f2d2b8089f857d0b4d39d2ff")
addappid(3857952,0,"8eacf347f1bc92ce4871593701eb46bbe34808641fc25cecbadab4cc3ee13c67")
addappid(3857953,0,"6e8efee3c623c35577b03ec14d0fb4c4a00022b7f12fbb4ae337da583397279a")
addappid(3857954,0,"ad90a12806a4ae9d5173de3eee0e2a4fb7a786e9ede87c1b31d2984a2fae9d7a")
