-- generated by KeySteam
-- update time: 2022-08-17
-- app_name: Psychonauts 2

addappid(607080,0,"689af17671d3e7773c5a27bee3e245449e6a720b81ded35366e764a7e132821c")

addappid(607081,0,"dfdca4a6e8f903ffd1a93290a893899e0726edc7a8c7b39fdff62b40c0994915")
addappid(3245600,0,"97164139d21ecf4706f9a240c1dcb2836ac7d533e2c434a027347281cd5422dd")

-- DLC: 1/1

addappid(3245600)