-- generated by KeySteam
-- update time: 2017-12-06
-- app_name: Helen's Mysterious Castle

addappid(418190,0,"8d60c6f7ad46f8672367be2d85efb608e09b625ad0ee540de6dc07311d3845f1")

addappid(418192,0,"2481254d64b31e47d5875275fd5d46a56ed98b908b85471869ddfa6ca94f6dcf")
addappid(418193,0,"562128d97cca3223040b093d2e5d4cb9d9304abf424853c2ed247a69c0b90083")
