-- generated by KeySteam
-- update time: 2023-10-03
-- app_name: 末代君主

addappid(1741040,0,"c2a3335a5c5cb18b7b352bcf3d5b094599713e8c932e80a7ff074980002c9d62")

addappid(1741041,0,"42ecf885d603358a87e3e2d1c021c5e7f2801d41f0adb0e5949317a30d134cdc")
