-- generated by KeySteam
-- update time: 2023-05-04
-- app_name: Puff Town

addappid(1742840,0,"e712300db0e1cd9d137652c85aebb08d9e6072427b435da2da840889054f9fcb")

addappid(1742841,0,"4ced2e4c98b409cbf1ae9de01bdd0f133da23761013a2563514422e922ec4e9d")
addappid(1758610,0,"d7cf06c2ff55b20cb32004e455a27ffcfe7d9d55cb7a07780cbe6ef049bd113c")

-- DLC: 1/1

addappid(1758610)