-- generated by KeySteam
-- update time: 2023-01-11
-- app_name: 米莱依优与幻惑森林的甘露

addappid(1743530,0,"98f1aec9b3d6f0b0c487dfbb9c1cf0e74989f315baab70b32c7c72cfea579715")

addappid(1743531,0,"138cab1f61e14709deddae7eec945c1a4d390d7de6b23431ed1e0101e438242d")

-- DLC: 1/1

addappid(2260830)