-- generated by KeySteam
-- update time: 2021-10-07
-- app_name: 家犬勇者与魔王之城

addappid(1747330,0,"a90f30b41ec2127d3eb910f6b7ff36d704e893aee76ffa892c9a2bb25320b01f")

addappid(1747331,0,"13774bd6c42e18f408e012783486acd0802048822b7088854d2928ad17464e3b")
