-- generated by KeySteam
-- update time: 2025-03-14
-- app_name: The Jackbox Party Starter

addappid(1755580)

addappid(1755581,0,"aeeb74b74b94bec0bfddd61e1a9f6c17aae14be679970d8eb0030394ead303a2")
addappid(1755582,0,"8e2ca6c76f3a664d9cc158d646418970f48ef904993c9be26cf4f807f0223bfe")
addappid(2828508,0,"86a8e078c58ea7fbf57bdf1b2611116fe069f5e590cfa11058ca6610e0961700")
