-- generated by KeySteam
-- update time: 
-- app_name: Qora

addappid(304460,0,"ea16af64a12e4c3a0838c5253704a52fcca05c82ceb34b456e9af52f17e04ac7")

addappid(304461,0,"5f4b43d3501ba4f5a66513edf3f22324e4123067504a0887808816efdce409d9")
addappid(323290,0,"bb64407593b98d39ead5b41642a6d98c5e734910b97cd1023b042e8274ddf884")

-- DLC: 1/1

addappid(323290)