-- generated by KeySteam
-- update time: 2023-05-04
-- app_name: 某旅行者的偷拍相册

addappid(1480340,0,"7f2bdd63cffe740c16b19406a4cdf52455c13d596d4496ad19eccef7111da338")

addappid(1480341,0,"030bd6e5851a0781fa4d2368732ddfb69b91c24e7f9489211b23b38061050487")
addappid(1494130,0,"55ff62cadd22a212c2bc24fcb0e9c00b1867721a6242f01d696500ffcc0a8bd5")

-- DLC: 1/1

addappid(1494130)