-- generated by KeySteam
-- update time: 2021-03-09
-- app_name: 秘密舞会

addappid(1494190,0,"1ff8efc66320d4d54290ce5c87093630ffd55137d601d3a827a11e57f701e750")

addappid(1494191,0,"6f44acfb2f1f4efb058c837c9af3aae02f295b4857fc1a4fe908659940a6775d")
