-- generated by KeySteam
-- update time: 2024-10-30
-- app_name: 孤狼 OTXO

addappid(1608640,0,"e2769e9df2cfffb2a7e9de79124cf0eee9591c7030c46330033824d883e9ce58")

addappid(1608641,0,"1bc1d0a1e2499d9575a5814e5c01c15664f11e1813d86e56f10766e78757584f")
