-- generated by KeySteam
-- update time: 2023-10-29
-- app_name: Kin's Chronicle

addappid(1617800)

addappid(1617801,0,"5550898b8b0640c2e62bcf4b0a0d8cffcf122ea40bbfb04fb83971138bc11106")
addappid(1617803,0,"9164fb9689bd64abf32b67e35bce586708292aef22fc9f5798b1da274a407822")
