-- generated by KeySteam
-- update time: 2021-07-15
-- app_name: EroPhone

addappid(1506280,0,"d0b450db8ac55570c7effd9d95ba315afabb788e2b50d2149c13a71d419ca9f0")

addappid(1506281,0,"68ea5ca95dee740307df15b7f1848adb3be96d4391021e9e30d094ad53b4ca9b")
addappid(1594550,0,"8fa3a6fcbca0601d848bdb5e859fd10b8795d6bdb87dff46bd8e18fa7b78e071")

-- DLC: 1/1

addappid(1594550)