-- generated by KeySteam
-- update time: 2026-03-07
-- app_name: Femboy Futa Mania 🌶️

addappid(4280140)

addappid(4280141,0,"5ffc3f35214b72ac14ab27af6f3d328035cad5798a90ad723fbce40be1a9b5b0")
addappid(4491310,0,"8e93e74386349f103db15671e6173f6285d61ec2b1cf39bffda432bb899d950c")

-- DLC: 1/1

addappid(4491310)