-- generated by KeySteam
-- update time: 2026-05-01
-- app_name: Sex Apartment 2: Grand Hotel

addappid(4284680,0,"66f0002d5b24732298ecbf57cb62af55c9bef17ce0c7bce17e58bb0d705b8fc2")

addappid(4284681,0,"e618e31cf943e8bb5d040ba04261d0c9ee985c77ae8b8e0bd94bb524ae7121f0")

-- DLC: 0/3
-- missing DLC: 4386860, 4386870, 4386880
