-- generated by KeySteam
-- update time: 2026-05-01
-- app_name: Sex Apartment 2: Grand Hotel

addappid(4284680,0,"66f0002d5b24732298ecbf57cb62af55c9bef17ce0c7bce17e58bb0d705b8fc2")

addappid(4284681,0,"e618e31cf943e8bb5d040ba04261d0c9ee985c77ae8b8e0bd94bb524ae7121f0")
addappid(4386860,0,"ef54473ff06933a9d45affd2eeaa62e985b258077a8b5fb93e53009a40b3c4c5")
addappid(4386870,0,"a568282d80829ad1c7532686067a71213c95ecacea6f91d889a99b788cc42acc")
addappid(4386880,0,"ae58c600c1c941a76c7c562844726c3a9b17e71732bf9882fbcb076e4d564bce")

-- DLC: 3/3

addappid(4386860)
addappid(4386870)
addappid(4386880)