-- generated by KeySteam
-- update time: 2026-02-16
-- app_name: 魔法变态果汁大战 -Magic Hentai Juice Battle-

addappid(4285070,0,"acd77ef82c2f08056a802c3c89f3dab91513150f9e6552c86e02fc7cbbf11e59")

addappid(4285071,0,"6cfde41b6a9e636cfc9a698b9a2a8bff3f6b5008d3b9c01a5041825d4502136c")
