-- generated by KeySteam
-- update time: 2026-03-03
-- app_name: Truck Mechanic: Dangerous Paths - First Mile

addappid(4292050)

addappid(4292051,0,"23f5deb7a1d0d972ddc6bb7292878d5031b3ed0958d59f56c5342a4187d6e3e3")
