-- generated by KeySteam
-- update time: 2023-05-04
-- app_name: 欲妹幻想

addappid(2203030,0,"22b3236f1f31488dcdccc0e33b109ba980a51e1051ca68d3e399a10a6f3b45f6")

addappid(2203031,0,"8d6abcc0d9a14955afee854f6371adeae98f98929b8ad8b2dd9e25217ca65e61")
addappid(2212980,0,"b6c27b7125fad2b9cd4138e4ba13662e7ac5d9e413a140a952d35b973078a4ee")

-- DLC: 1/1

addappid(2212980)