-- generated by KeySteam
-- update time: 2026-05-21
-- app_name: 乐高®蝙蝠侠™：黑暗骑士之遗

addappid(2215200)

addappid(2215201,0,"5d2bafc1381c29ebabb37bbab50e496548be24f6bf5d511e8d471b99d60cfbf3")

-- DLC: 5/5

addappid(4168610)
addappid(4168620)
addappid(4168630)
addappid(4168640)
addappid(4468750)