-- generated by KeySteam
-- update time: 2021-03-07
-- app_name: Attack it! Devil legion

addappid(1106060,0,"031e08c0941ba356a075590b94fcf59897d100b59c73ab5c73a41f20f8962910")

addappid(1106061,0,"b3b4aafe513dbcf68675a375c73a071d2c6042a43c4becd89d22ac1eca37ee79")
