-- generated by KeySteam
-- update time: 2023-11-28
-- app_name: Windjammers 2

addappid(1114290,0,"208c09d49992e40c5e23603c64cedcc39ddc9c41175fcf7f56c2bda9482f9984")

addappid(1114291,0,"a55dfa12b90546b6cf95904006f8842f1e7a86682d220f72f513369d403b9955")
