-- generated by KeySteam
-- update time: 2026-05-25
-- app_name: 平行人生 Paralives

addappid(1118520,0,"e52365d9e88efee525a3978c4991cad62a7f1bf6a53054dc6b38df387bc8dece")

addappid(1118521,0,"20543823281f3ef968fcd728fafb6786a33991bb918fbce88cd0a5c7fa49eb5a")
