-- generated by KeySteam
-- update time: 2025-12-26
-- app_name: 伊甸守护者-密林之拥

addappid(2672430,0,"75593a21055b0d494e4e874b92e7d1fa7b521758f465026e2392cc4cb81bf717")

addappid(2672431,0,"53f8addf6dbe106b60b6a48ed701f3466dadf54f9368b2993ead9ae5f0652588")
addappid(2770454,0,"b3f9436d2a8efbd8866167c867cdc6a3cd2b83d6e187e9fd43587ff52fac2549")

-- DLC: 1/1

addappid(2770450)