-- generated by KeySteam
-- update time: 2026-03-06
-- app_name: 阴界诡录·尸语公寓

addappid(3941850,0,"f995d1e148d2296d017684496a8fab2883ce14881dcf8078b213ef51258dbd99")

addappid(3941851,0,"98f1646c2d30ac898451a1e489b3d45cdce064dad5deecbe545765c943a00e02")
