-- generated by KeySteam
-- update time: 2024-12-24
-- app_name: 修仙•母珠传 Pig Training Legend

addappid(3262320,0,"721dd6ce56ce4d1de929bac53d00e282cd41b9de7d4dad2261d1444c505127ab")

addappid(3262321,0,"f7e001ed53f7bd875d4829c18c215c9112ae8a429efcf86acda4eed829a6fa77")

-- DLC: 1/1

addappid(3262460)