-- generated by KeySteam
-- update time: 2026-04-16
-- app_name: 吸血鬼爬行者: 屠戮地牢的吸血鬼幸存者

addappid(3265700,0,"20f9ef13db9be4cd2b66262d177c6107c74912a164f5c1e519d194e090bc57e6")

addappid(3265701,0,"1e7525ea73ba61b029745bf11a16c0f88090e25fd8a3841cf7c06879636857f8")
