-- generated by KeySteam
-- update time: 2026-05-04
-- app_name: Chubby Story

addappid(3277170,0,"db96c951516345f657c95389d54402c170af46c9cd0ac413b558398ca424ddc4")

addappid(3277171,0,"cc8696abd7532a825d4fe57acca530ae9edbd12277de44522463f36f40d1ca69")
