-- generated by KeySteam
-- update time: 2018-09-07
-- app_name: ZONE OF THE ENDERS THE 2nd RUNNER : M∀RS

addappid(650510)

addappid(650512,0,"f45d939a07bc038a0dabf47c1f170ff94286b5eb344b5e770218f8481dbe48ad")
