-- generated by KeySteam
-- update time: 2024-05-14
-- app_name: 三国很忙

addappid(2814650)

addtoken(2814650,"8419173057748207867")

addappid(2814651,0,"06705512aa1c3fe8c5ef69487dcc17488656a0732fc9e01c40f1c4b032545772")
