-- generated by KeySteam
-- update time: 2023-11-09
-- app_name: RESIDENT EVIL RESISTANCE

addappid(952070,0,"990bfab2b62fccd8a91a20579a65b8578b6b583785cbd89264bc1ca6c9b2947a")

addappid(952071,0,"be4c331b420fccf7ed6e4ed528a8f004574c409dfc941ad3e7004fb936679301")
addappid(1108280,0,"2c80f9e638cea673510ec5562456040bb00c6ef138fb7be77c691ecab6118199")
addappid(1295350,0,"dbe021a1825f0f53da71272f5fd0f4e37669b27d0e00393fcc472b70f515dce7")

-- DLC: 2/2

addappid(1108280)
addappid(1295350)