-- generated by KeySteam
-- update time: 2025-10-14
-- app_name: Cat Quest II

addappid(914710,0,"e8cd6c551bd5f17646b284181092286b768c120f3260ab59f6f13a2e1b214238")

addappid(914711,0,"7a9034278cc1f859bc64f942f36c04f11d114e9073a512cf40c1e14b12682ea3")
