-- generated by KeySteam
-- update time: 2022-06-11
-- app_name: SNKRX

addappid(915310,0,"fe9fc8cbc1444fe98a95eb411c1119b386316994a163ae154171b5b69b2a4d82")

addappid(915311,0,"a402f6b0f6f23994e293e2d8d0dc951268cfd288d3642ed643280231a0636fc3")
