-- generated by KeySteam
-- update time: 
-- app_name: Saturday Morning RPG

addappid(263320,0,"ca83c4924641ccecea6c43a18adae796d99dfa4d851e06f5f2ef480aad48f77c")

addappid(263322,0,"307d9a70c45700e15b0cb0c2a1306dfc1c11cbbb4e92d6c73423e8a1aca7ba3e")

-- DLC: 0/1
-- missing DLC: 325640
