-- generated by KeySteam
-- update time: 2024-12-27
-- app_name: 成年人填色本 2 - 家庭版

addappid(3309510)

addappid(3309513,0,"1786714cc1bebda5a1ee227fad8362641fce6920f32647a61e59d72d2f9734e9")
addappid(3311290,0,"2c93d8661e757b2c0c106f90e665cae88febbc47eef90f6de87fb6984cf84684")

-- DLC: 1/1

addappid(3311290)