-- generated by KeySteam
-- update time: 2026-05-14
-- app_name: 今古群侠传

addappid(3313720)

addappid(3313721,0,"ee11efd6a3f4b69b34662632aa725443ff59d29d7c5f5b17f2c02414af66623b")

-- DLC: 1/1

addappid(4599150)