-- generated by KeySteam
-- update time: 2025-07-28
-- app_name: Damsels in Distress

addappid(2526160,0,"1dcd53154942101a0e53cac9fe3bd4d9ce15629d5700629aeabef8f7222eeef4")

addappid(2526161,0,"451ebfef8061d4063eaf5e09ae7ccc9b06852a0044a0bd4c7c2a8c29121f0278")
