-- generated by KeySteam
-- update time: 2025-06-27
-- app_name: 米塔 MiSide

addappid(2527500,0,"319708828feb58fa2ed02fb00975af201afbd79269c7f91a3a5e69efcf51f4c0")

addappid(2527501,0,"ffef2d1f42cd2438f5b7d029d771a9f941fd224250c3184f595773fb4926e1cd")
