-- generated by KeySteam
-- update time: 2023-09-29
-- app_name: 规则支配

addappid(2528120,0,"0f8110b18452f1a6b76f1344e56585c17baf1dfb5be27d44de379f2b3a6f1ae6")

addappid(2528121,0,"7b8af7d0b6cd85e44eafc69a954643a85d1d19671ce8b5475ae946dfb22b9b0a")
