-- generated by KeySteam
-- update time: 2026-04-13
-- app_name: Self Defense Dojo

addappid(2534120,0,"831ab5fde71598aff2adcc46b0c62b1c623531992d8f9572f0ec2e6f58763c3e")

addappid(2534121,0,"d59188b9f24874801e3b610eb5ca4e5485098872f5c980e5fb2906d38ec98c7d")
