-- generated by KeySteam
-- update time: 2025-05-23
-- app_name: 黄毛漂流记

addappid(2535770,0,"cd1aba5b1ccbcdf78ba43433bf9176a6497e7b6783ede9a0e22e31b5368ec660")

addappid(2535771,0,"e63408e639d3e5bac5344c02be0a9a0b2afdff7fbcc07353212f91fbf0efab01")
addappid(2767190,0,"f00d963fb6b766112946037767cecf16d02ffc74076949ec7439406dc6049f0f")

-- DLC: 1/1

addappid(2767190)