-- generated by KeySteam
-- update time: 2026-05-14
-- app_name: 疫区档案

addappid(2537470,0,"aa1e8d876524d8c495c9b043d20254c652c4e6aecb91e0d00f4ba4df91941523")

addappid(2537471,0,"eb134c55a5c37809375328873020b52202229a54f2f8202764b320c507b3ffcc")

-- DLC: 0/1
-- missing DLC: 4491260
