-- generated by KeySteam
-- update time: 2023-03-01
-- app_name: 探灵直播

addappid(1523400,0,"2e9053b98840d784f2f4383e6f15a0067079a14647f9e729e4b3e266ff1f9b6a")

addappid(1523401,0,"265f6150389c0e2aa58e2072a3fe0a5ecb77f51f4f624a9164aeb498ab240f8f")
