-- generated by KeySteam
-- update time: 2024-01-31
-- app_name: Jerry Wanker and the Quest to get Laid

addappid(1525050,0,"1fc87e0069d9b45c302c86333a5af4854aff64060fbdbe7ada9d7f68350eebce")

addappid(1525051,0,"d5d151c97fa1c979dc6effe5c355a6ea78fc1f08af0dc0daf1e29dae01fac767")
addappid(2595520,0,"1136e954f9119f99f4b7b89c7a254babdb2698a904367c213ad050957171e45a")

-- DLC: 1/1

addappid(2595520)