-- generated by KeySteam
-- update time: 2023-03-19
-- app_name: 重回哩世界

addappid(1527630,0,"461c34df9d578ff75633817a8f8c08619886c0890e9d28f38f3439de958b0a95")

addappid(1527633,0,"912dafe6d862688705f3fc895d7a36f3ca5e11cb550b8e254d584cec045d8bad")
addappid(2204780,0,"fe60188dd0036a1f103e8ab605a3bfb6fcc70b013ccfa4f52555be1a965bb407")

-- DLC: 1/1

addappid(2204780)