-- generated by KeySteam
-- update time: 2024-02-15
-- app_name: 超级偶像 

addappid(1529990,0,"08a048fe8d4035407856a158d31deaf8174f69d455336267fb28d1e54cdf95b9")

addappid(1529991,0,"74e3094018de4704a22dfd5c8604136c0d5be31dc8cc352a5eccd238870ed84d")
