-- generated by KeySteam
-- update time: 2022-03-11
-- app_name: AstroBike

addappid(1539600)

addappid(1539601,0,"083efa9f7a65bf6092e884db552effc894ddd3f9be897338acacf05f9920e228")
addappid(1539603,0,"ed033b0ec5ef2c6645a022c9d74421897a72f7f35d0593957a0887a6c67fb805")
