-- generated by KeySteam
-- update time: 2023-06-26
-- app_name: 圣骑士莉雅丝

addappid(1097370,0,"59e8126019524223d5b556ea790d27ce00dfe826630a41d89df064367d342b13")

addappid(1097371,0,"ebbd318c18cf0cb59b16e9a854d0bd962807978682eb9a865ddb8ae9c87321b7")
