-- generated by KeySteam
-- update time: 2023-01-11
-- app_name: 梅里娅与恶鬼之岛

addappid(1720040,0,"034cef310efc8896d81861025ac40cf1f20a9b624f707c3c70eccff6eac8a82d")

addappid(1720041,0,"d450f34ed8c767727bb92ab0af0b21d70f5f78ba9d4e4dcd9e2eebddde44dbb2")

-- DLC: 1/1

addappid(2260820)