-- generated by KeySteam
-- update time: 2023-01-13
-- app_name: 魔拳师莎拉

addappid(1724840,0,"0b13de295235b6fe8b2c1d8483f0a55a7d6fc35f9802c3de648074b723f64b1a")

addappid(1724841,0,"149900ef25cfcaf4c4b4e306cf90fc4f0429f6ac12a9270b37becaa6e924a2d4")

-- DLC: 1/1

addappid(2460830)