-- generated by KeySteam
-- update time: 2023-01-06
-- app_name: 精灵之妊 -用怀孕征服所有傲慢的精灵-

addappid(2108290,0,"bbf7b815d590c674a86f9c6eda35d0393e704db6e993d8836b08e2a80d258afb")

addappid(2108291,0,"269074d0cc0e614ac9bf05aa8d5125fefa1e7458224f180e1782790aa306244e")
addappid(2183300,0,"6784bb672c730e98c30658f77d2b5500d4ffbc183052262b34d7f445ff650a1a")

-- DLC: 1/1

addappid(2183300)