-- generated by KeySteam
-- update time: 2026-04-20
-- app_name: 冒险家商店

addappid(4165310)

addappid(4165311,0,"9153920d3d36325c625304683a68bf9e8aecff17ada098341cf9622715893799")

-- DLC: 1/1

addappid(4604960)