-- generated by KeySteam
-- update time: 2026-02-01
-- app_name: Operation: Outbreak

addappid(4169300)

addappid(4169301,0,"a0da85c49fd116dd27c8eb8511f6de34899f345677d37928f69242346906de72")

-- DLC: 1/2
-- missing DLC: 4179630

addappid(4307940)