-- generated by KeySteam
-- update time: 2026-04-19
-- app_name: 汪汪大作战

addappid(4575390,0,"4e444a90af78c5333c69a0fa873da3c8f23ff6fa75d1ddd1f066b1ad62ba319d")

addappid(4575391,0,"5db43126ea3762c201898ae2e6b08c448e65d75e9fd759804c40a9b2b6752166")
