-- generated by KeySteam
-- update time: 2025-01-25
-- app_name: 王国英雄III

addappid(772430)

addappid(772431,0,"f15f5d60baba89f047b13e36559da0337deabaf2cb570e7fc865b491cece3dd7")
addappid(772432,0,"c54cb3a1786139c0ba1d041b58b16e5b3a31d256f73f22589bfc32d4424b14d9")
