-- generated by KeySteam
-- update time: 2020-12-18
-- app_name: Stygian: Reign of the Old Ones

addappid(779290,0,"efe41badbd2e36f4f7fcede2bc0af5d209b702ec25f93d1c56c3ed26dae9d9c2")

addappid(779291,0,"37f873aaa02255795220c926640e8ceca09ce3fbe9b85686f17f18fe84f7d2e1")
addappid(1160140,0,"5f8df459ccbdf1db750d30565e861ce7e233124786d7c428cb6628919d91b7fb")

-- DLC: 1/1

addappid(1160140)