-- generated by KeySteam
-- update time: 2026-04-14
-- app_name: Wanderburg Playtest

addappid(3624200)

addtoken(3624200,"9596375404454862001")

addappid(3624201,0,"32e88db8227556ad852cf5329e8570e1ce42e961ef061b01f17aefebb9d09c57")
