-- generated by KeySteam
-- update time: 2025-11-08
-- app_name: 将异世界收入后宫!

addappid(3633740,0,"6daeba764a015e55adcaa20bf5cb7bf8cee0c1dea1f47704a3624db7aac55045")

addappid(3633741,0,"485183ddc49c62748ae8534d59bfaf84a4c9a2cd5029542404aee7fd76a697a5")
