-- generated by KeySteam
-- update time: 2026-02-24
-- app_name: 甜蜜魅魔之家

addappid(3225060,0,"e39392fa8531888aa636278190d134175b73b9a2bdd491ed76e5b723ac8bc835")

addappid(3225061,0,"841b30619da002ac7b7e92a5089c0027e7afd52f6d122b5d5446ae851bd920da")

-- DLC: 0/1
-- missing DLC: 4118770
