-- generated by KeySteam
-- update time: 2026-03-18
-- app_name: 吾家有女 Ai

addappid(3227670)

addappid(3227671,0,"c9204cfcdec28e64d4eecfca04a6b634519ddbabd333bd8a5c952c272a6f77d8")
addappid(4126050,0,"4501b15b9bebf793b03a3275b643096cbabb751062b117435c0615d677b20b20")

-- DLC: 1/2
-- missing DLC: 4497890

addappid(4126050)