-- generated by KeySteam
-- update time: 2026-05-07
-- app_name: 蛙穿雪境

addappid(3232380,0,"618a064aa1b2d1ea7e3e34622f2894d4c3828e4dda84752e672e778d9dcb266d")

addappid(3232381,0,"69a2aab568f099e226d1009d82828af5b12d8db2a7a78e52142c033c606be7cd")
