-- generated by KeySteam
-- update time: 2026-03-12
-- app_name: 机甲浩劫

addappid(3237920,0,"04ca759b2c1a73fc3c82f68cdba0dab211123f0735c8bfd87ec69b0bd0727a17")

addappid(3237921,0,"712fa088f2f4af47a1f7efd96fe4ffacb43bdc542af472ec48e6619dae2b8378")
