-- generated by KeySteam
-- update time: 2023-02-28
-- app_name: Sakura Succubus 7

addappid(2021710,0,"44605f57d8e9dbe3cc4134b27a2c5fa762cb111ab023d74e7736d0dfe5634714")

addappid(2021711,0,"0bf1786c91a524e3b5e99ecf6996797554d143e20e70ac8f4ca10dd908370d91")
