-- generated by KeySteam
-- update time: 2026-05-02
-- app_name: Die in the Dungeon

addappid(2026820,0,"817d01838bdc09e36667907572918d49fd19b3956bec066afbd456b63e9db04b")

addappid(2026821,0,"891341488c8e6e96d7c8551a5d56799ea66ea333322887007d3b892cd866d249")
addappid(3450700,0,"50dac3d62042ea8d2835fbe69f718e909e38e1c3e36dd2ee2cb0e709c98f70ca")

-- DLC: 2/2

addappid(3450700)
addappid(3956760)