-- generated by KeySteam
-- update time: 2026-03-21
-- app_name: MY PLACE IS CURSED

addappid(3201440,0,"8169caec5da480307c8e174f168475da190fd4df410d3747b94bfdcbb0f1c6e4")

addappid(3201445,0,"31e77d645dc92f9e6d1e58852ee7bfdd448a8bdbb027eb47594d9c1904bc76df")
