-- generated by KeySteam
-- update time: 2026-03-02
-- app_name: Space Lora - Adult Only

addappid(4343280,0,"caa56d40d9a51120090201bf508911573de98614644c4586c669d0e031d70a92")

addappid(4343281,0,"e27926c9fd75be59f5f6fffa4107daaa41f4f633d4cf7cd14167ffb49e67d476")
