-- generated by KeySteam
-- update time: 2023-04-24
-- app_name: 沙石镇时光试玩版

addappid(1645320)

addtoken(1645320,"2024128723523268368")

addappid(1645321,0,"0bea428699d47fb257e2a78aca54d02f266e2bb92e3cf77b697cc8dae40f1cfd")
