-- generated by KeySteam
-- update time: 2022-03-19
-- app_name: 股市之狼

addappid(1658310,0,"c68fc6de0b11a656b4547b46162b28b039129fc7875392876799f1b6b45ebc77")

addappid(1658311,0,"72f3fe0fe313e79a07afb879d48f8a264b67f2879cc5197c471131d9fe0a27c6")
