-- generated by KeySteam
-- update time: 2026-03-18
-- app_name: 伦敦旧影：信抵之时

addappid(3725910)

addappid(3725911,0,"aef4d7ef260ff16bdec0abddc83dc4992b08660410a046b22aa5f8b730b80f1e")
addappid(3725913,0,"ed3ac88153e67bc5c8b23c9e9a32974769b73279382f4f2831021fe85ea9872d")
