-- generated by KeySteam
-- update time: 2025-11-26
-- app_name: Clappy Cheeks: Lust and Magic

addappid(3732100)

addappid(3732101,0,"7d28152df79c77de63860ccfb50d0ba86b6f9b314b2fd1d2b20353adc7e00a68")
