-- generated by KeySteam
-- update time: 2026-05-01
-- app_name: Flock Around

addappid(3618030)

addappid(3618031,0,"9d63dd57e66e2d55e88bde8007ff230f542748c6da92938b9e551528e45b77d7")

-- DLC: 1/1

addappid(4585870)