-- generated by KeySteam
-- update time: 2023-04-08
-- app_name: IamTheExorcist

addappid(2320270,0,"ae7edb68ca18c0f2ba9ac75f7aaaed4010ecf2f3c9617f8fe3983c1cdb2635b9")

addappid(2320271,0,"5d7d4d581af97640c2bfcccc54e825f51b11502ccb34d62daace32dea37f13d8")
addappid(2324720,0,"ab5ff41aa2959290c69697a536d07053713debb34bd03d22dd1e75dc2040fe25")

-- DLC: 1/1

addappid(2324720)