-- generated by KeySteam
-- update time: 2026-04-03
-- app_name: 幻想乡：有罪推定~夜明前的三色堇

addappid(2325310)

addtoken(2325310,"2863926897060389178")

addappid(2325311,0,"893b2ebfd37db2518e5b1be2c1560fc8c0d4607e8cbd1d0dcaaa811c272c8956")
