-- generated by KeySteam
-- update time: 2026-03-19
-- app_name: 绯夜传奇 Remastered

addappid(2331020,0,"ba3faa2ee3c8f345222ffd462c28e1487657e9044dd19677a6a62467b997b2dd")

addappid(2331021,0,"4c296709f48c48bc8fb38dde91a407523d6563d56af48d5b741f79e4c088b990")
addappid(2928060,0,"a155487ed7105b9c95c700d97886764d3724978fe369e84bffa0b5fb6c65b85e")
addappid(3157650,0,"5ffac903e2bc90905dbead2653a94a129f37c64ccc8a0175f588649955ff0e82")

-- DLC: 11/11

addappid(2928060)
addappid(3157570)
addappid(3157580)
addappid(3157590)
addappid(3157600)
addappid(3157610)
addappid(3157620)
addappid(3157630)
addappid(3157640)
addappid(3157650)
addappid(3177880)