-- generated by KeySteam
-- update time: 2024-02-15
-- app_name: Sweet Beach Holidays

addappid(2332660,0,"f6ef4af9bd62d6b5ba7f81aa30ac5c109e516cb4291abb2ac1d4929e4c873928")

addtoken(2332660,"10412364603393434765")

addappid(2332661,0,"8b247f96220f819c8e6bc50e7c67ce166ccd00a69b710a37b59318cc19ee37ca")
