-- generated by KeySteam
-- update time: 2025-12-18
-- app_name: Landnama

addappid(2339040,0,"3c6cc5b8328a610a71d1acc25c83f22309bb1cd2b59cad325aaab4bcd4332dd8")

addappid(2339041,0,"46789bf5b7b445274bd3e5f4e35e2a26254ed0824ed96b19a003632f6e45e864")
