-- generated by KeySteam
-- update time: 2023-10-10
-- app_name: 上古女神

addappid(2120850,0,"ea8c2b8523a100e6dbf26c1cc341bb3146f5a93e4cd105e003ad886005a3e770")

addappid(2120851,0,"0ab529516172a1c96230d0c18f1389a11294a8997de1206bd0ce5e172f757abb")
