-- generated by KeySteam
-- update time: 2024-10-23
-- app_name: Socrates Jones: Pro Philosopher

addappid(2120060)

addappid(2120061,0,"db2100a4c7ac053d0ae2d86fc899676597104a2c76a56fabe81daf83dfb41eb2")
