-- generated by KeySteam
-- update time: 2022-09-12
-- app_name: Miss Kawaii

addappid(2125120,0,"d3d1aa471304f0f98987affdb2b38c745faa68a39d8a5b2bbacffccec1d5b382")

addappid(2125121,0,"608ce7be438a35d7510550b67e116c06bad3425aab7b7c9435f00198e87e8cba")
