-- generated by KeySteam
-- update time: 2024-05-23
-- app_name: What the Fog

addappid(2139020,0,"bb97624e86693819c6915e30b3228012d77524c25f4bbaa308e9f4f9c209727a")

addappid(2139021,0,"02f0f2b85e4ca82606c390c02c614e8c9d90d912d1d8a36decf3865c9fea443a")
