-- generated by KeySteam
-- update time: 2025-10-31
-- app_name: 将军 对决

addappid(2084000,0,"1414b3a0486bd3189691c8d2647997c6cfc15b5fe5018dd464612ebbb05dcd49")

addappid(2084001,0,"e467a1dc28688a4ba159328e3419a2ddbbc265d7677b0eff56c56d25954271a9")
