-- generated by KeySteam
-- update time: 2022-09-20
-- app_name: PongPong Girl

addappid(2088040,0,"98cb1897738874f1fb479840da930599f3e82e3b8defaf8bd30ae6e9d5472dff")

addappid(2088041,0,"8d24c65724568cb506053aa6f58074f0f109d10214a6259addf7bf18cbc8dca7")
addappid(2098980,0,"170b355155c5e28f0c681f99dc61ddc0a16bfedb4e651f71672b300bac4a9e18")

-- DLC: 1/1

addappid(2098980)