-- generated by KeySteam
-- update time: 2023-03-06
-- app_name: Magic Tower & Maidens

addappid(2090950,0,"179a3bd39b0e5fe701fd4f46e9b7ebfda14b09b5904074bd3f61fdb5652148f9")

addappid(2090951,0,"f5557f7522ea66e99accef81e11706a04791d7744e12859c6ea7eeb3d71c6061")
addappid(2307270,0,"0d2ac020edfe02dadc2819647c32b28fc4b2e4289fa19f8fb5003bf1e0e51777")

-- DLC: 1/1

addappid(2307270)