-- generated by KeySteam
-- update time: 2025-08-23
-- app_name: 赌神模拟器：亚洲风云

addappid(2091550,0,"894e2363e4e2bae21dfeb7e1cf07e3e72aab6b59a95dd42337e4bf69b0f3f6a9")

addappid(2091551,0,"b6863c86e01e38ffc8fd3e4370e9f503e3bff12fdb0f78a2e9c34cf679566419")
