-- generated by KeySteam
-- update time: 2023-12-04
-- app_name: 基因战争

addappid(2093980,0,"1efabb5a5f8bc62f290cd600fe3f6b245115d2349a615bda86b63c7de9acda8e")

addappid(2093981,0,"b1520573567df9016b95576a1af0da36b8f86189b8953927f19b8641498c406c")
addappid(2093983,0,"dea1ab6e007e57326dceaf77d42ffa74ced0804be90b3d4ba7687ed4831894a2")
