-- generated by KeySteam
-- update time: 2025-01-28
-- app_name: 原子之心

addappid(668580,0,"5a1ed8d8d2a8110fde9be6e0ec543d96db83954f381710c70e330b5c010841e7")

addappid(668581,0,"b331448756a6614f7b9b52f56b71e329928370afb8034b8474e264ace0048928")

-- DLC: 8/8

addappid(2214820)
addappid(2214821)
addappid(2214822)
addappid(2214823)
addappid(2214824)
addappid(2214825)
addappid(2214826)
addappid(2214830)

addtoken(2214825,"5039941091422940824")
