-- generated by KeySteam
-- update time: 2019-03-07
-- app_name: Solitaire Mystery: Stolen Power

addappid(679820)

addappid(679821,0,"a867d0b70fe732af9b8d1164011ad5614b6f896a11135dd4134f394954a818a1")
addappid(679823,0,"b4ef8a4430b167b930a77f5d893657c6d93c54ad572069d02fb338eee7d5ba8f")
