-- generated by KeySteam
-- update time: 2024-08-05
-- app_name: Universe For Sale

addappid(1627840,0,"7215e5640d6561d5975056a9f2334f896b088e9a9a73f6964ff8824ca76e982d")

addappid(1627842,0,"6308dc6c54f3773651969a6960bb1245a71bd0fbab175820c857264de3ad6983")

-- DLC: 0/1
-- missing DLC: 2676510
