-- generated by KeySteam
-- update time: 2026-04-24
-- app_name: Magissy

addappid(1636460,0,"35b9c10fb4fecca60e533c1dcd06321dc48d7e8280e5c37c6dbafc01b6fee5bb")

addappid(1636461,0,"1a16d9ebfbd5ec0f237897d3d5b6e6b54f182961ae215a3473fc3d20357a6f9c")
