-- generated by KeySteam
-- update time: 2022-08-09
-- app_name: 与神相伴的末日

addappid(1639930,0,"e797aaed3f8fafb38c332ebf8e119de03df3a563bf2d927b1f13a3404cced8a5")

addappid(1639931,0,"3651882622fc5fca5acac782010e3b2aeb33797dc527c2bc46a45c068dfa97b9")
addappid(1639932,0,"f38e78f66b783263282cee75e00d246a3b9115c1027759076051bb7c09e5edc3")
