-- generated by KeySteam
-- update time: 2026-02-12
-- app_name: Astra: Ardent Show

addappid(3970070,0,"3f8ddb4feac46cd52438c7aecb6f5f060496c69a3186b59d66a59e9ae10fe5bb")

addappid(3970071,0,"f8521dcf108491cd5cbcf8635b124e079ad53e81bd98b2b41936e99cd345f6d1")
addappid(4238250,0,"f302c34cdb99d9aba47146c172e98147856d9604c033c371264361297d615a30")

-- DLC: 1/3
-- missing DLC: 4238260, 4238270

addappid(4238250)