-- generated by KeySteam
-- update time: 2026-01-10
-- app_name: NEKO-NIN exHeart SPIN! LOVE+PLUS

addappid(3971880)

addappid(3971881,0,"6594052068fa8b380207c46713173fc475a403f8edeb33fc47e663ab3b77d4b1")
addappid(4231610,0,"9b05e8df32d75e77cf59677f750118739210d9524890df55417ab58c6dce2655")

-- DLC: 1/1

addappid(4231610)