-- generated by KeySteam
-- update time: 2025-11-17
-- app_name: 奥特罗斯 Ultros

addappid(2386310,0,"65bbe1aebfe571e2ae6d25cd91a2572866b7a2419ce405528cb246db22724259")

addappid(2386311,0,"af749a581922a0c97f5cd9d034f04d877796b39acf48e7a430aae7f3dd52a852")
addappid(2649730,0,"f30ea3d32d7bed49f7fb1180aa43a34f94cb972fdaf4e804172aabe70fefa3df")

-- DLC: 1/1

addappid(2649730)