-- generated by KeySteam
-- update time: 2026-04-23
-- app_name: 战斗卡丁车

addappid(2399430,0,"179c52e9c9ff705dd19b9f42ab7b44cd9111990195c50bb9566fd810176f284b")

addappid(2399431,0,"d86d1b9b0561a6404cf7da28d757baf3a7b5ca28b393118f1ff74ac5dac5b91c")

-- DLC: 0/2
-- missing DLC: 2653800, 4108340
