-- generated by KeySteam
-- update time: 2026-04-13
-- app_name: 王国：两位君主

addappid(701160,0,"a870b8cb617fd6f06ec9d1b0a89f514f8611794aa043288467001423108182c7")

addappid(701161,0,"5aae8ca5c454854bdf1b25248fe5f3c01a97c983489767c17930cc8a02156ac3")
addappid(988810,0,"09f7b9d014059b08ea21838c59e9edadb8d14238c0e97a6cbb6d597d98f49174")

-- DLC: 8/8

addappid(980450)
addappid(988810)
addappid(1299270)
addappid(1708680)
addappid(2736340)
addappid(3062350)
addappid(3062360)
addappid(3939430)