-- generated by KeySteam
-- update time: 2017-11-08
-- app_name: Elise the Devil

addappid(711990,0,"cc6ad41adf35714454b81b9585d69bb86c56bc94eb4bd73e4d90101c159134a8")

addappid(711991,0,"43e23dc10ff4a012a2cf4a0d6c6f05aec79fa655adabf5ce391bb90cafaf1e5a")
