-- generated by KeySteam
-- update time: 2017-11-10
-- app_name: Fallen Times

addappid(712810)

addappid(712811,0,"a00bddd08710b3d2c63097c8636a14f596a52f5925f7c5447da945d4002a45c7")
addappid(712814,0,"4cc2a68d1ff70e146ba086c0bc032b309f55820c74a3e14fe2667de6f5819fc9")
