-- generated by KeySteam
-- update time: 2018-09-19
-- app_name: King Exit

addappid(712840,0,"ba71cce5f3a14e7383aef3e246229445a84c9bd80a606a2be2a60b9c2b5bbdcc")

addappid(712841,0,"913ca9f5894eab832835ee20916df2db429e0027e30cbba2fc8fccab2972724f")
addappid(929360,0,"b7dd2420173e11e5b3a201c00fe54d47ade373e7319dedea069b0cf8699660a3")

-- DLC: 1/1

addappid(929360)