-- generated by KeySteam
-- update time: 2017-10-19
-- app_name: Taima Miko Yuugi

addappid(719430,0,"3a8e2eb0a47055d60ee6b1d1eb95f8e6d9132132606b9d7f1d1d22907ed28570")

addappid(719431,0,"cde0a12fb04721436c8470fd87527d9f399fde08c59899413d655ff161acf970")
