-- generated by KeySteam
-- update time: 2019-06-27
-- app_name: Zanki Zero: Last Beginning

addappid(819020,0,"cb6b953e994d84fd5c0ddac6a15dde2b815343d65b41156162c20dd7134f4924")

addappid(819021,0,"ec9e19564d0aec8730421340231c83ae821404a166da55fb92991871d4421db4")
addappid(1060910,0,"4a45a3b50bcad5e21dea5382aa42db77de849c879706411920c656c4c2b8c415")

-- DLC: 1/1

addappid(1060910)