-- generated by KeySteam
-- update time: 2024-11-20
-- app_name: 秋空回忆 -命运的地平线-

addappid(2795550,0,"c0cb0927af028957ca8b2f906abf55217f6804f585048744b1f302e6106b97f9")

addappid(2795551,0,"b5ae0cb6b10e023f0f94176b595a4e82e8f1f92608904cdc9d2a6e27a391ced3")
addappid(2795552,0,"3444e96bf3933a354e20a7a02b801bc507e17eedfabfca8a32a5e0c256cc89ff")
