-- generated by KeySteam
-- update time: 2024-12-07
-- app_name: 武林至尊传

addappid(2797000)

addtoken(2797000,"8720048237580684073")

addappid(2797001,0,"a4a761588b39610ee69755f6727f74a88c38bee00cb06f07aeb8b1bfc80c4f7e")
