-- generated by KeySteam
-- update time: 2019-01-25
-- app_name: Sakura MMO 2

addappid(968950,0,"a1c5bfb3286594d1e3654c327fed05345bc9708a4467a6863c9234f69fe68016")

addappid(968951,0,"2e2b834a3aaba6e6c0a68ddb9548518abcceeb46441774f969e90d308aba1b11")
