-- generated by KeySteam
-- update time: 2020-01-17
-- app_name: Lost

addappid(1126290,0,"655e0c8d815c81c8cc37da03a2d87280f79b942d285583e51aebef26a42bb56a")

addappid(1126291,0,"e83afde6761301fe3dbc6dac26b94aa751ee4ce3d24a50ee38514c8a6f235a42")
addappid(1163360,0,"4f4490ab394740bafe11a590c479b8c1583c8fda00a8315648de7289b2d986c1")

-- DLC: 1/1

addappid(1163360)