-- generated by KeySteam
-- update time: 2026-04-13
-- app_name: Barely Working

addappid(2241000,0,"80aedf30d982bd53f9759486a262ff56e13b8f9896a15e23f3b2fddb964e89f4")

addappid(2241001,0,"12377d561b721a07e1e0e23d78270d84eb59abed891f07e8e054913686124956")
