-- generated by KeySteam
-- update time: 2024-12-26
-- app_name: 战栗绝境

addappid(2246460)

addtoken(2246460,"9124649371652244618")

addappid(2246461,0,"5be5e731ac4aa8a2941108870c75e6099e1ecc99c40effb58e815fb2f92dae40")
