-- generated by KeySteam
-- update time: 2026-05-05
-- app_name: 互联网大亨

addappid(2249340,0,"15d02ca9805e6dd1cbf4f6c753fc4c41a20861b07debbcc2eb92107f554b3023")

addappid(2249341,0,"b7d06a8b55ea4201850617f895acbc393256a21e6ec1c79e6ea7340de3847228")
