-- generated by KeySteam
-- update time: 2023-06-23
-- app_name: 复兴游记

addappid(2250270,0,"807cd04b299769647bc6d9192321b130f454b807b29f5f5b42f9a4e5f4eaed2c")

addappid(2250271,0,"c4820a9f356ab8a417e372a10a0862ee49896f4dd783a827fb7856832ff7eb2c")
