-- generated by KeySteam
-- update time: 2023-03-18
-- app_name: 斗技场物语～盗贼与姬骑士篇～

addappid(2257840,0,"1972f29176c45d1aefee1d7230850c6891eb497e936fe5fdd9f30e02b864c9e0")

addappid(2257841,0,"5954945f8491022c0b111b4ebdab6a37fa2daec1564c56779703b258da7a2cc3")
addappid(2301720,0,"64c88f86f3585e25652e487cf442945ee7f1dbe2798554f8af80b23358b8356e")

-- DLC: 1/1

addappid(2301720)