-- generated by KeySteam
-- update time: 2026-05-06
-- app_name: Turnbound - 武装博弈

addappid(3802470,0,"283045d92bf4a156bb5b16f3cc8b21eff20b4dcc2e2ba81cf1b1a41ddc8dff66")

addappid(3802471,0,"442c7d3ae80e78480b3ee434166c940f7dfad83b2c876b0223c43ac080a6f2b5")

-- DLC: 1/1

addappid(4314960)