-- generated by KeySteam
-- update time: 2025-08-07
-- app_name: 修女索菲的秘密花园

addappid(3817570,0,"9d1f9c994368aec980fe13d9535bc28e1dcdb4e751c12d8536407254a5258bf5")

addappid(3817571,0,"27a31a4a5e358272351938ea72ef41d8737f7280f101391b50ca9d8d89b1d2f8")
