-- generated by KeySteam
-- update time: 2025-06-09
-- app_name: 无敌号

addappid(731040,0,"cb50ed9f9b095aaa21cf2c23bbc01c3e5f9370cca589298022437bc3f5932441")

addappid(731041,0,"82179143c4f409cdc0851cf2530e75f827cc5ce893e9eb95859146139ecf7f01")
addappid(2622920,0,"14917a90d1ac4fc46a4819fac3edaa31e63643f67fa7e33af624d7893a36e89a")

-- DLC: 1/1

addappid(2622920)