-- generated by KeySteam
-- update time: 2026-04-10
-- app_name: Crown of Greed

addappid(1697870)

addappid(1697871,0,"fbb7cc5a010587be482a97583b5a31774bc9f2fe7c1adada0c1448f0d80c4578")
addappid(4527750,0,"c4e5e3a281de3be9d872c1a95de026fd248d187e978b01e3e7206dc3df503457")

-- DLC: 1/1

addappid(4527750)