-- generated by KeySteam
-- update time: 2018-02-16
-- app_name: 影子武士2

addappid(324800,0,"3c2e8a336b4bbcfa345851c1fc4356af042fe84951d62f4ca11a86856fe653fd")

addappid(324801,0,"c7d42c521529297c5a3a3174a89a1fb9084a0ec10f56c3de7c0a5c5c9d9134f1")
addappid(522335,0,"2d94068eca43f9b19c6d3910e732094c9579796e5a6581d1d72e53c4f8c972ec")

-- DLC: 9/9

addappid(508970)
addappid(522330)
addappid(522331)
addappid(522332)
addappid(522334)
addappid(522335)
addappid(565840)
addappid(592460)
addappid(592461)