-- generated by KeySteam
-- update time: 2017-07-08
-- app_name: A Bird Story

addappid(327410,0,"aaa0224fc14a539a8c75f2177e78349288135c7beb638b8dd3ccaf10beeaf3b1")

addappid(327411,0,"05d2ff6e229db03e2fdfaefe4086aa6b6dc05b13626f141da7fcb40ad4089433")
addappid(328230,0,"0724e3ff26927d38665292645e8dbe4970a7156e84c86c0e3efe58bffd4980ae")
