-- generated by KeySteam
-- update time: 2026-05-09
-- app_name: TetherGeist

addappid(2474430,0,"78912c1d5230519f4a17ca14269f56a26c0566f161dff0eb1e50438b1260477d")

addappid(2474431,0,"572ea146209713c8b7487150b512b652eb5d79b2a47417aba9c89fff9227b170")
addappid(4641470,0,"1349ddeb8f039b06bc8d395aeb521f297fcc5013c532546fecc2ad93dcacc34e")

-- DLC: 1/1

addappid(4641470)