-- generated by KeySteam
-- update time: 2025-10-03
-- app_name: 深海迷航：冰点之下

addappid(848450,0,"9124a368510557262677476613a2f852f3c6fa6b2de59fd46093edeeda2ae65c")

addappid(848452,0,"2faf06aaa2ceea761e8a38f7f8f72d4c64e3768d5e94c600e3c671f2eeffa17e")
