-- generated by KeySteam
-- update time: 2026-01-29
-- app_name: Five Levels of Love

addappid(4127820,0,"769730f4fde6ba236565c3d1f60e3c4f3183cdcdbaa74d130f8c476e227475eb")

addappid(4127821,0,"1fc0c485285bb32e72322e9f06670113ec656aa55901c217ae48a97455248fd9")
