-- generated by KeySteam
-- update time: 2026-04-16
-- app_name: 竞拍之王

addappid(4128580)

addappid(4128581,0,"4f74fc9947de95eddfad71e6c6be2abf0b55b2f096917fab98728d2f5f37ec12")

-- DLC: 1/1

addappid(4464600)