-- generated by KeySteam
-- update time: 2026-01-15
-- app_name: ASS: PRESS F!

addappid(4131510,0,"f9c186afeeb6efa793bd539e81192c4e55e141e38dc24b278d9bf46120dc066e")

addappid(4131511,0,"5e14ddb3dc71b2a30f3ca1f6bca39836522513969a5c0280e0bda6b2e1a43e2c")
