-- generated by KeySteam
-- update time: 2025-12-19
-- app_name: Scream ～After～ Short Story

addappid(4134510)

addappid(4134511,0,"e888f21da5689ad6a8e5a8d65197163970a41a762d4f034363b46e64164ef2eb")
addappid(4134512,0,"e6efd7ab400bf4e4d6fd631f231bbffd63081e1e05a1d147326f6ea6869c1165")
