-- generated by KeySteam
-- update time: 2026-03-26
-- app_name: Rest Area Simulator: Prologue

addappid(4428790)

addappid(4428791,0,"1d2ffc1d6a38c0273e277598eeac2354037958036177f27bcdfc0d16775516eb")
