-- generated by KeySteam
-- update time: 2026-04-27
-- app_name: 异世界餐酒馆

addappid(3570940,0,"d9df87a82504fe07effb0872756434d6e7287fc8519c6552e127c496f361d91e")

addappid(3570941,0,"fda6e87cead70aa7bd022e1e4fa314b383fe72dc4f6ebf4bbe5c9a367e3055f0")
addappid(4591781,0,"d279897475d270125126e3d22f62f9773ebc3955ea222f8b414685ab94f046fc")

-- DLC: 1/1

addappid(4591780)