-- generated by KeySteam
-- update time: 2026-04-18
-- app_name: 余火守护者 The Ember Guardian

addappid(3570060)

addappid(3570061,0,"515cabaa91c90fa4e194cfbff43b0055eee2f728c633897d9ee39de78ad6bfb7")

-- DLC: 1/1

addappid(4501320)