-- generated by KeySteam
-- update time: 2018-05-04
-- app_name: River City Ransom: Underground

addappid(422810,0,"4387494df6e488de148be6d18a8f82f3cd1aa701c3aad770103f180c5e6e07c4")

addappid(422812,0,"88732fc4ced9dbf78dfcb5d7d0d181f30e10cf46447381dca312546ba0392c7f")

-- DLC: 0/3
-- missing DLC: 598510, 598800, 598801
