-- generated by KeySteam
-- update time: 2025-01-23
-- app_name: Empire of the Gods

addappid(436140)

addappid(436141,0,"5767acb3c2d8595bd39ef788e7ea081d6720a84827b0d5cd86cc4db2bad9f654")
addappid(436142,0,"e62fcb86078bd6c822f3c10a5ad17a41f833a9ddc0eee2bb67ffae8aaee6c6bf")
