-- generated by KeySteam
-- update time: 2023-05-08
-- app_name: 隐居军师的救国战略

addappid(2169830,0,"e506d404e64ead88be4d8207834700c147e43d76cb4392702399ba37b0fa706d")

addappid(2169831,0,"50729f57297b7958292cbe0f33ce70aa83e010759ed60e6eb411604df8b407d9")
