-- generated by KeySteam
-- update time: 2026-05-07
-- app_name: 古神之呼唤

addappid(2174380)

addappid(2174381,0,"b23891968a4d2f805a9d01cb4c6f8ccd8f498fdd22b105ff97a529c07d159c0a")

-- DLC: 1/1

addappid(4656660)