-- generated by KeySteam
-- update time: 2026-03-12
-- app_name: Cobalt Core

addappid(2179850,0,"8120f900ce70d975ee9ca8c6c0d0aa4aebe4662b800b42f3a0e5ee7ccf361f8b")

addappid(2179851,0,"bc615c0333a243446cace8a2e902062b5450891478f8a8468c419bca793be235")
