-- generated by KeySteam
-- update time: 2026-05-08
-- app_name: 黑暗密友：望升院

addappid(4157130,0,"1e806df0d813f7535ef9a407b17e3fdc7c32a201142a64fd158ba707d4f4593b")

addappid(4157131,0,"f0553aec8a8550b7deee04cf5eec6bc0b3fd13a407b189a4201260b5c9198251")
