-- generated by KeySteam
-- update time: 2025-10-14
-- app_name: Marimoth

addappid(1786660)

addappid(1786661,0,"b544f24e1ab9720bcaa374b076ff44cb4cd15a50db1158c0a175b57ea546cf9c")
addappid(1786662,0,"bb3e1e34b20bba59aeb3e48b467ec3cdfac88b26024bf05fbfe2df671d539a12")
addappid(1786663,0,"0e3b9d0e876025df01a59e0989d8c66423fbc2264d8d50e968606e0f27191c92")
