-- generated by KeySteam
-- update time: 2025-06-22
-- app_name: Monster Girl's Labyrinth

addappid(1789470,0,"4e65699ac8dd3c6dc4a972c14e802788cf735e95198acd904f4a12704e1ff6d0")

addappid(1789471,0,"4147e6435a64bef28d7bf86528f65617e7ba8f9f9666c77371f3d4ed9a3d6c09")
