-- generated by KeySteam
-- update time: 2026-04-14
-- app_name: 终落之城

addappid(2706020,0,"1e77dbc1e9853e8b3745dc5f83ea2f91a1a6235c8d318ce3b2d16c5396d90ba5")

addappid(2706021,0,"8ca6191f4f09dcb309688901e511599e604be2d09f060774e028dce04bd063e3")
