-- generated by KeySteam
-- update time: 2026-04-26
-- app_name: Cycle of Corruption

addappid(2709090,0,"7aaac95afc52559f6bf3e56aae6b183ce3aa94f24934ae44024b2d12c70c98ee")

addappid(2709091,0,"15f215ed95c43b217eeecf0ab25da70a62fedb1a8dab9e8e61c0abb9fb3b99ba")

-- DLC: 0/1
-- missing DLC: 4593740
