-- generated by KeySteam
-- update time: 2025-01-31
-- app_name: 虚之少女

addappid(2712550,0,"b6461ea94b1458730dd18ffe249e349bb482fa485bd488a84d33a8b0903c0d0c")

addappid(2712551,0,"62bf645b1fe806fa53c687c2496e5f15184506cc091583f0dc6b86f6d6dc1135")
