-- generated by KeySteam
-- update time: 2026-04-14
-- app_name: 指尖疾速：打字狂潮

addappid(2400160,0,"bc1dc17e7b12a68b0572fdca97a4a44d1611fb04ccda23b4d6ea015ea880076b")

addappid(2400161,0,"6f7a7948926c54ef401bd49c61a850798da9f1f1ec4ce4bc0f92379aa836327c")
