-- generated by KeySteam
-- update time: 2023-07-29
-- app_name: Hot And Lovely ：Violet

addappid(2403270,0,"7d35d0abe33c301737b5dd99a21145b48a83dcdaccf1858e552067e8bb33fcb0")

addtoken(2403270,"95485299265960393")

addappid(2403271,0,"da3c16cca2d307ce4f1d9446bfec3fb3223fd290a342cbb0e5f1ba6956cb8f1c")
