-- generated by KeySteam
-- update time: 2024-04-14
-- app_name: Parina's Demon Lair Adventure

addappid(2405330)

addappid(2405331,0,"6dafa97adc5131a8678102baeb4aa55241de7eb62f38e73169ea57b1a8637ab0")
