-- generated by KeySteam
-- update time: 2026-04-02
-- app_name: 放血医师

addappid(3493400)

addtoken(3493400,"3659762617034554995")

addappid(3493401,0,"8a6abb5aad134d861c0a29f71a53939beb784d0c3cf5d5cb5ee9dc99695c0191")
