-- generated by KeySteam
-- update time: 2026-04-15
-- app_name: 妊星少女绫音

addappid(3592210,0,"d8487f69d551f569953765a96a5cc8fc3864247b6c93d36adc93fe95630ae36e")

addappid(3592211,0,"b2d752548714cf387ec6426e68e4a1f018d6d3242cebf8ec376f01296251c09c")
