-- generated by KeySteam
-- update time: 2026-03-29
-- app_name: Lust Arcanum

addappid(3593520)

addappid(3593521,0,"bd6bb10ab70cb52f63ee37b59c309351e8e2533a9eff71ef0186bca783665200")
addappid(4507250,0,"706e0a861ad5a7dfaea32a97174a3ce5f8dacfd33b6df7716b0e6a7b7bd6c0a8")

-- DLC: 1/2
-- missing DLC: 4288870

addappid(4507250)