-- generated by KeySteam
-- update time: 2019-12-09
-- app_name: Osmos

addappid(29180,0,"6d6591794681c127753d51f9eee8d73d220e72afccbb8a7decb2b27e9d603587")

addappid(29181,0,"d0c47e8295db1ca538e2428678f22c7f2bc280c1e4490f466f9095ca3c2c4290")
