-- generated by KeySteam
-- update time: 2026-03-03
-- app_name: Only Mining - Cozy Digging Game

addappid(4381240)

addappid(4381241,0,"6c39e0dffaa053a0e423678f12fc5b79a7c0de2a184ea713b2dbc95730bfcacd")
