-- generated by KeySteam
-- update time: 2026-05-02
-- app_name: 驱魔与迷途修女

addappid(4382900,0,"90fa13f014c80b9b03a2c6750291e272299ecfae17d579fb4379ee684a809370")

addappid(4382901,0,"81bc971dedf534ad3b20b62f2d1bb9cc289dd68f5c5d02d42cf0b1db30734b93")
