-- generated by KeySteam
-- update time: 2026-03-26
-- app_name: 人外美少女体液饮料店

addappid(4397430)

addappid(4397431,0,"6b32ae066fd34a66a3a15c34cca5f6394bc05a5fbcbb17da3e684f9b0fe7be7e")

-- DLC: 1/4
-- missing DLC: 4401730, 4401740, 4422630

addappid(4401720)