-- generated by KeySteam
-- update time: 2022-03-15
-- app_name: 二次灭绝 Second Extinction

addappid(1024380,0,"6addbb8b8a5014b849f0a7d998286284fd6587e747ce74e5ca746e1d660914e7")

addappid(1024381,0,"6af0fd07101ec6ffc837645d413cdce5b0f5170ddc3363b882007e346ee24b8b")

-- DLC: 4/4

addappid(1414350)
addappid(1414351)
addappid(1414352)
addappid(1414353)