-- generated by KeySteam
-- update time: 2025-05-10
-- app_name: Third Crisis

addappid(1260820,0,"8c2a2633d8ee998562148b0323e6788ef89a3401fcb992df2dd75a265496e0a3")

addappid(1260821,0,"852ca57fa9da1bba259bddd26ebf6114b9ee327ffaa4c4e7197e7e30596cc99f")
