-- generated by KeySteam
-- update time: 2024-12-27
-- app_name: 戰鬥公羊

addappid(1262060,0,"de986de67a72887ac926d07ca7bc3ecd970a786f330fdf454a2309591c93c543")

addappid(1262061,0,"01ca2ec553286309609c3c1a09678ca759dc696a64d07ecc40a5d79937a340af")
