-- generated by KeySteam
-- update time: 2021-10-22
-- app_name: 邻桌女同学

addappid(1268870,0,"7f9935c4c9c1ba8497d3b6457f573b701908150c5c54168de3d4a11f9c4c0b7d")

addappid(1268871,0,"d2478e151f5b413407ad2b894c85bfc186eee14252ebfca63b70f1f3072483d9")
