-- generated by KeySteam
-- update time: 2026-03-02
-- app_name: 桌面舞娘

addappid(4322000,0,"2ec3cf67b99fd62c224e106021e9338ca96c59aa6952e7f4960ab413fd68fa41")

addappid(4322001,0,"25c3b2bafd065ae5601fff90f270c61bad02eaeaff83514a3427e0b4e6fc16da")
