-- generated by KeySteam
-- update time: 2026-05-21
-- app_name: 巴萨卡狂潮

addappid(4337210,0,"308f4416ef126a00cdaaacc631dbbe0ab0031c15c1a760ffa48008c72931baae")

addappid(4337211,0,"5d55f21c3271b923bce573758432b55e21a9f51be06dfb2ed848633667e28c3a")
