-- generated by KeySteam
-- update time: 2025-11-17
-- app_name: Crop and Claw

addappid(2760970)

addappid(2760973,0,"2f1f4d58e26fa588c5700e17743ee9169ac308cb94a728873592086eff29415e")
addappid(2760974,0,"37a8be934890c9b04f3d3887c8cb86fbfcff480c1a82202282311106f1a4c5c7")
