-- generated by KeySteam
-- update time: 2023-11-14
-- app_name: 战乙女终焉之歌

addappid(2229480,0,"0a686bce4b1721cb24081ace66bd63cb2b48b5aab67727284dc2e8085ef72c11")

addappid(2229481,0,"2736059c3388f121f5325344fcea134abb20460bd5bd72c448475d844a84b208")
