-- generated by KeySteam
-- update time: 2017-02-23
-- app_name: Sunrider Academy

addappid(340730,0,"f7fbdedb95989b5f51f2f3cdbd4456ad4cb31710db08603aa9c4fd4adadcdf04")

addappid(340731,0,"a8514c0c66d6e948d64a83b67737bb7f0add7d28050919fe59fb5cfaa9f87974")
