-- generated by KeySteam
-- update time: 2026-05-19
-- app_name: 符文之骰

addappid(3542380,0,"60cbc1ad1877f3f0d1dcc3d2b2369f797522668ad960f0b72cdd15ce4d4252c5")

addappid(3542381,0,"31d465c765aa06e4d5586a3829ca8090d4980c2fb0edfea602d8fc38b2059378")
