-- generated by KeySteam
-- update time: 2026-04-25
-- app_name: Kiss of Sin: Rewinding Flame

addappid(3551620,0,"748d1a7d9ec06b4950c2e8c0e2329a97af9d231dfc3aa6c2048970eea6fd5186")

addappid(3551621,0,"839ce5f6923feb1be0158bcd4f28dfd3926af5b6b34b36d1daeb912322536407")
