-- generated by KeySteam
-- update time: 2026-05-12
-- app_name: Retro Rewind - Video Store Simulator

addappid(3552140)

addappid(3552141,0,"8527bf46fe5454e6c8956a042fb1aee9a9792d7f4c73ebe85ab6924dfcc1c0fe")
