-- generated by KeySteam
-- update time: 2026-04-23
-- app_name: Do As I Say - Obedience to the Priest

addappid(3558880)

addappid(3558881,0,"c7a211f6824f057919a9ac5d42e3a5a17a2048557acce72d22962392601b7819")
