-- generated by KeySteam
-- update time: 2026-05-23
-- app_name: 恋人日常

addappid(4272540)

addappid(4272541,0,"f9567ffbae07ae203edc1521a8b1202445fab5f626da378f6b3bba23794c45e4")
addappid(4272543,0,"f155cc17a68a7d02cef4e7e2c80855faf2d64beeea7e3613dedbfcb786b3f8a6")
