-- generated by KeySteam
-- update time: 2026-04-16
-- app_name: 莉兹与萝洁的欠金工房 ～负债姊妹的炼金日志～

addappid(3143550,0,"ad3d0c6ee518ed25632727036c27cb4693ca84ff9f3bf8149e56e8d28e044db1")

addappid(3143551,0,"7a96dd1d967de43b52b6e214ac03b37e9b3accb86e4885d22b85b0f0d316643e")
