-- generated by KeySteam
-- update time: 2024-09-25
-- app_name: 循环支付

addappid(3143560,0,"445b91071e3f0f2626532ea8837e7018a98f081aee36fdf8075276c7806aa050")

addappid(3143561,0,"c5f86521d21370c54bbcd29b140b8bb4850f1b56de005aba445de8278ddc1c5f")
