-- generated by KeySteam
-- update time: 2026-03-26
-- app_name: 亡灵装饰

addappid(3155570,0,"bebe75f3086498ec7fe872d033ddc968fd547cce3454860cf8d52290e3175229")

addappid(3155571,0,"8ef5395dabb534f305266ef1061a89790f78ad60842d3e044f04df5c37321432")
