-- generated by KeySteam
-- update time: 2026-01-09
-- app_name: 每天都跟召唤出的克苏鲁少女玩桌游

addappid(4181690)

addappid(4181692,0,"c3fff4e79c96cbea2981cdc21157819d06fa713a2e10803e1510363ebb9ccc26")

-- DLC: 0/4
-- missing DLC: 4186780, 4186790, 4186800, 4204480
