-- generated by KeySteam
-- update time: 2026-04-17
-- app_name: Samurai GUNN 2: Free Edition

addappid(4375060)

addappid(4375061,0,"678e7d3e25e068a2868b7ad514a0dbbef1306ed727ff698a0e82b799ef0b9703")
