-- generated by KeySteam
-- update time: 2022-05-02
-- app_name: 异世界无厘头生活2

addappid(1423080,0,"81ebf4843a77aa368ee13d7e815229d181c31ab371ffed3feac201fc33c7b00e")

addappid(1423081,0,"660028547e257a0f5b3c5d86ce5fbe8d7d36761e1562ed083750db34b1aa5b66")
addappid(1968560,0,"0199c9614ef5192bf2a1708625f21a6538031e1af7c1913ac17cc2dab54e245d")

-- DLC: 1/1

addappid(1968560)