-- generated by KeySteam
-- update time: 2021-09-28
-- app_name: 旋风战车队: 速度城赛车

addappid(1434330,0,"4fc2bc05158087dcf6cdc0489989132921af2399f0492dbe18d0d2d14b9908a7")

addappid(1434331,0,"54b132e3f91e91a89e9c7aed944fe37eda5baea4cd65207496d1bc1f80b01108")
