-- generated by KeySteam
-- update time: 2023-11-30
-- app_name: Hello Neighbor 2

addappid(1321680)

addappid(1321681,0,"3b7358ea38b82be2ea05fbd1d4b8271a15bfa62beea41f7682d0383073dcc0be")

-- DLC: 3/3

addappid(2215320)
addappid(2215321)
addappid(2215322)

addtoken(2215320, "7949074578561629775")
addtoken(2215321, "16142866641829250492")
addtoken(2215322, "102581051070664829")