-- generated by KeySteam
-- update time: 2020-11-12
-- app_name: Tower and Sword of Succubus

addappid(1327080,0,"0876b0ac447ab01d5b4f1eae4f6ac5946bef1c87200c3475771d51d304d2f9aa")

addappid(1327081,0,"cb2b4add371e439241034149f122fbe8dfa23554d90909006c73d5e3dbe93ab8")
addappid(1404680,0,"4303eaee0a90e3962f37e575661e426dd6609a816256e83816a0a27569a36759")

-- DLC: 1/1

addappid(1404680)