-- generated by KeySteam
-- update time: 2021-06-23
-- app_name: Tower of Waifus 2

addappid(1560770,0,"a18881e35cbd2f2b623fccd5433a4d4f9f9c965f72289110a231eb3703573d6f")

addappid(1560771,0,"3aa02449c5684f32c58b4adaa2a9637f6eef2cb6e120b14f1289a3cd7f4bb889")
addappid(1639270,0,"e20d5f17c60b2da9502a72a799ffe1829f1213e3cd83fac4592b2c9c8d41852c")

-- DLC: 1/1

addappid(1639270)