-- generated by KeySteam
-- update time: 2023-07-07
-- app_name: Operation Sexy Sudoku

addappid(1567050)

addappid(1567051,0,"86623622060628ae0bd2d3cf4d57bc02aed8cfc7649593a17b6fb25c90bd9cd5")
addappid(1567054,0,"5febf3fe01b788ecf50d49400ec5daaaf4ba28f53e5c81a7b34f1e68c33781d2")
