-- generated by KeySteam
-- update time: 2021-11-02
-- app_name: WISH Paradise

addappid(1573300,0,"7fc914a269df53ba37cbd3754ff362d76b5ad6e3c4a53806c206974ac4354260")

addappid(1573301,0,"c1bd2b9897236f6a2e098b2e368d85ad926f2e67f1d9b461ef94c58eff617b8a")
addappid(1616180,0,"edb1facc601d2bb481f67c934550ac7207e41d30a54c64823b3d720c26e18176")

-- DLC: 1/1

addappid(1616180)