-- generated by KeySteam
-- update time: 2023-04-24
-- app_name: Resident Evil Re:Verse

addappid(1236300,0,"999d2ac43f1c8862e62d1a523efb1018449e26d3a26b00119e60f23bca19468e")

addappid(1236301,0,"d871901d18077503a33843f0aed308396db2824654f75fe5217f6ed3c91f1de7")

-- DLC: 9/9

addappid(1607011)
addappid(1607012)
addappid(1607013)
addappid(1607014)
addappid(1607015)
addappid(1607016)
addappid(1607017)
addappid(1607018)
addappid(1607019)