-- generated by KeySteam
-- update time: 2024-08-17
-- app_name: Polimines

addappid(1892790)

addappid(1892791,0,"98eb106fed97dbc8c7bc2f3617a93e4fdf2b9c0a53b73cdf5c3c59cbfb7614a0")
addappid(1892792,0,"533f22cbf7f05a23b5165b089cf04182e2946cd5e56414850523b3b4162ce71e")
