-- generated by KeySteam
-- update time: 2026-03-25
-- app_name: ASKA

addappid(1898300)

addappid(1898301,0,"32c13d15c0ef56699f2d009163b995a3a06463310ea381191d1d19e332af2f6c")
addappid(1898302,0,"b6944936716bbd335558b942182ae2cc1ed5de90e4eddf954f5be9be6248017e")
