-- generated by KeySteam
-- update time: 2022-07-02
-- app_name: Rolling in the Maze

addappid(1899400,0,"a1307d05878a0bdf80ccfa72b7535def44c6878042f867d277e22fd14f785a55")

addappid(1899401,0,"629bdf244ecfcab1c289082c0c3231f452a92267d80c64a968da7269a5e026e6")
addappid(1908590,0,"94874b40ab6f5cb089d7df33ef54a6747737e89f6b7e7c872ceb4d5d7857f4e5")

-- DLC: 1/1

addappid(1908590)