-- generated by KeySteam
-- update time: 2026-05-15
-- app_name: 红色沙漠

addappid(3321460,0,"dc014470e47064263f3003feb526a87cc64784292e2a608455d18fa70ec2c1e0")

addappid(3321461,0,"e2e570c84eb8b4cfe9c20268cd30b84f8c1c7c076691c92ae8c5ba7b510b8a95")

-- DLC: 3/3

addappid(4024620)
addappid(4024630)
addappid(4193060)

addtoken(4024630,"17135069641874014023")
