-- generated by KeySteam
-- update time: 2025-11-28
-- app_name: 冒险者肉便旅馆

addappid(3333360,0,"5804deb85ef9e2ba779299ab4772d9c14173cc7a52a8133c74ac15e0d06c6f86")

addappid(3333361,0,"9ac11bd4159f8498c395295fb035e0d13b60de9445deca014a27938537396c82")
