-- generated by KeySteam
-- update time: 2026-05-02
-- app_name: Ataegina Act I

addappid(2929140,0,"327b1aad2e7899afadcbda25c559ab830fac2f4c0ef5c97a67f84cc14e3c00a1")

addappid(2929143,0,"007d93289ac0cf899cf8c695611aed5b3d9e04720e6c8e56d93bd4a37fded1c7")
