-- generated by KeySteam
-- update time: 2026-04-13
-- app_name: Outhold

addappid(3767740,0,"0a7fc916f3b34078c17cbdff6101fb9f59fbf33a9a984e8b07a469a0aa9e9e36")

addappid(3767741,0,"97fbb25eacb8358b777d45b36c5a08a6cadb9260f44a15944a73764e84c01278")
