-- generated by KeySteam
-- update time: 2026-02-12
-- app_name: Snow x Hime

addappid(3771570,0,"20e57eeb32bb73244baeb254c73456bc3643787ec4c3801cfe32b075800c8a62")

addappid(3771571,0,"272466db7b3e91f193817e7cd020c2724d0ecbe6486db57b1890fcadec758a7f")
