-- generated by KeySteam
-- update time: 2025-12-25
-- app_name: 洗脑学园 - 咒人之壶

addappid(3773380,0,"b4b623573945587e09882838b6b2e54d5a33151b6fd856df16869126302a3ca6")

addappid(3773381,0,"e5fab4bdfdc513e3c8cb57d31f3cbf609591c1c0220333395beb7ce1d61d17fc")
addappid(3773382,0,"fe1c981b0e1afa2d6bac28c5e5b1534ef6a232cb769317192e68f95a7bb75c73")
