-- generated by KeySteam
-- update time: 2025-11-30
-- app_name: A Difficult Game About Climbing

addappid(2497920)

addappid(2497921,0,"89eba51d9ff7c9f0f6e85a64650d0744d02da8ad30dc61daaafe30062861ff88")
