-- generated by KeySteam
-- update time: 2026-05-13
-- app_name: SiNiSistar 2

addappid(4466620,0,"de887f3565af8aa5f3b2cfbf3cecc87912c521ae8e8bd441eafd7d8693715564")

addappid(4466621,0,"240a8767c6fcb561914f7c4495d7e5a9bf4dc0a2793a40d75351764b1eafa2f6")
